### ISSUE TITLE
Filter breaks when selecting one browser and not "all" or "shipped"

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#1]
Steps:

Select IE from browser drop down
Select prefixed from status

Expected:

Show features prefixed in IE

Actual:

0 results

Same for any other browser or any other status except all or shipped.

https://twitter.com/tomprogers/status/451911417646837761

**Comment by molant** [comment]
The browser filter only looks for features that are shipped so right now
this is the designed behavior.
How do you propose it should work?

**Comment by dstorey** [comment]
Either:

It should enable the shipped option to reflect that behaviour (and never show zero, unless that is truly how many features have shipped). This would still be confusing as the user won't notice the status has changed, but at least it won't show the confusing 0 features thing.

We’d need to do something to the UI to show those two drop downs are linked. Perhaps disabling the other status options.

Or:

Decouple the browser drop down from the shipped status so that:
- prefixed + IE shows all prefixed features in IE
- Inprogress  + IE shows all in progress features in IE
- In progress + Chrome shows all in progress features in Chrome
- Etc.

This would be the most clear, but I'm not sure if we have that data for all browsers? I suppose we can get some of it for Chrome from Chrome Status?

**Comment by molant** [comment]
Closing this in favor of #30
