### ISSUE TITLE
Add ECMAScript Internationalization API

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftEdge/Status#100]
The ECMAScript Internationalization API is defined by standard ECMA-402, a complement to the ECMAScript Language Specification. Currently supported in Chrome, Internet Explorer, Opera, and Firefox, but not in Safari

Standard: http://ecma-international.org/ecma-402/1.0/

MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

MSDN:
http://msdn.microsoft.com/en-us/library/ie/dn342821(v=vs.94).aspx
http://msdn.microsoft.com/en-us/library/ie/dn342822(v=vs.94).aspx
http://msdn.microsoft.com/en-us/library/ie/dn342819(v=vs.94).aspx

**Comment by dstorey** [comment]
This should be labelled IE11+ for the IE support info. 

We need a good way of syncing with Chrome for thing not tracked on their side.

**Comment by jacobrossi** [comment]
Thanks for the suggestion!
