### ISSUE TITLE
Add `beccapurple`

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#103]
Now that Eric gives his approval, we should track `beccapurple` on Status:

http://lists.w3.org/Archives/Public/www-style/2014Jun/0257.html

**Comment by jacobrossi** [comment]
We shipped this in an update to IE11.  I don't think it needs tracking on status.

**Comment by yuhong** [comment]
Which month's update?

**Comment by jacobrossi** [comment]
It was in the August update  in 2014
