### ISSUE TITLE
Add IndexedDB subfeatures

### ISSUE THREAD

**Issue by theodorejb** [MicrosoftEdge/Status#104]
(Filing an issue for this per [IEDevChat suggestion](https://twitter.com/IEDevChat/status/479694598491488256)).

The status site reports IndexedDB as implemented in IE10+. However, not all subfeatures are supported. Specifically, support for array `keyPath`s, array keys, and lookup of objects via compound index (see http://codepen.io/cemerick/pen/Itymi via http://caniuse.com/indexeddb).

It would be great if there was an item to track the implementation of these features on the IE status site.

**Comment by dcecile** [comment]
Because this data issue is still open, does that mean the IE dev team doesn't yet know that it's a real code problem?

Also... should I create a Chromium dashboard issue to modify IE status of this feature? Or is ["shipped"](https://www.chromestatus.com/feature/6507459568992256)  correct?

**Comment by adrianba** [comment]
Working on getting this tracked publicly. The three areas we're tracking are: Compound Keys, Indexing Array Values, and multiEntry support. They are in our backlog but not yet in development.
