### ISSUE TITLE
IE scrolling issue

### ISSUE THREAD

**Issue by am11** [MicrosoftEdge/Status#106]
I have found a scroll issue, when focus is on section element, with IE11 on Windows 7:
- Go to http://status.modern.ie/ and type 'download' in filter box.
- Expand 'a[download] attribute', 'Subresource Integrity' and 'Resource Priorities' sections.
- Click inside any of these section to change focus.

Now use arrow key to go up and down, the browser won't scroll!

There is no such issue with Firefox! 

Is this issue confined to Status.IE website?

If not, does it has anything to do with `<section>` tag or the CSS applied to it?

Connect bug report: https://connect.microsoft.com/IE/feedback/details/900506/

/Cc @dstorey 

<b><sub>Redirected from http://blogs.msdn.com/b/ie/archive/2014/06/16/announcing-internet-explorer-developer-channel.aspx#10536228</sub></b>

**Comment by jacobrossi** [comment]
Looks like an IE issue. Thanks for the bug report. Closing this here as the Connect bug will track the bug in IE.
