### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#107]
I suggest status.modern.ie to support HTTPS, so that if some external HTTPS only websites want to load status.modern.ie/features (on client side), they will be able to do that without breaking HTTPS.

**Comment by jacobrossi** [comment]
We've added SSL support for our domain. However, our data is sourced from a merge with data pulled from ChromeStatus.com, which does not support HTTPS.  I've [pinged their issue](https://github.com/GoogleChrome/chromium-dashboard/issues/105#issuecomment-47373418) on supporting HTTPS.

**Comment by jacobrossi** [comment]
You should be able to request the IE JSON feed over HTTPS at this point, but the site won't load that way yet since we're dependent on Google to update the ChromeStatus.com feed to support SSL.

**Comment by ghost** [comment]
Thank you very much, jacobrossi!

**Comment by ghost** [comment]
Since chromestatus now supports TLS (https://www.chromestatus.com), we can fetch its data over HTTPS if users view status.ie over HTTPS. Also could we redirect http://status.modern.ie to https://status.modern.ie, to be consistent with www.modern.ie?

**Comment by molant** [comment]
This should be fixed now via 57b09ec1a8fa73d3b70f0580fd0a29dee49e2993
