### ISSUE TITLE
Investigate removing bootstrap

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#11]
We don’t use 95% of bootstrap.css according to the Chrome audit tools. We can save around 1,200 rule sets and about 4k lines of CSS if we remove it. Should speed up parsing, page weight etc quite a bit.

Disadvantage would be less default styles for new content we add, but we don’t use many of the built in classes in the current code, and we have a bunch of overrides for the ones we do use.

**Comment by dstorey** [comment]
Published initial work at https://github.com/InternetExplorer/Status.IE/tree/remove-bootstrap-css

Not merged into development yet. After initial smoke testing locally it works the same as the current development branch (except the add button and focus highlight on the filter field.) Needs more extensive testing on Windows in the office tomorrow.

Not looked into removing the bootstrap js file yet.

**Comment by molant** [comment]
Fixed in 9bb93604e445cbadb2f4fda3639dc9bea101a921
