### ISSUE TITLE
Change srcset spec to point to HTML5.1

### ISSUE THREAD

**Issue by adrianba** [MicrosoftEdge/Status#114]
The [&lt;img srcset>](http://status.modern.ie/imgsrcset?term=img) entry should have the spec link point to the [HTML 5.1 spec](http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#attr-img-srcset) now that this includes the functionality.

**Comment by jacobrossi** [comment]
While I'm at it, should [picture](http://status.modern.ie/pictureelement) point to [HTML 5.1](http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#the-picture-element) also?

**Comment by darobin** [comment]
@jacobrossi Yes, definitely. Thanks for being so amazingly responsive (no pun intended :)!

**Comment by adrianba** [comment]
Yes.

**Comment by jacobrossi** [comment]
Looks like picture is already pointing to the right spot.

**Comment by dstorey** [comment]
@jacobrossi I updated it in response to https://twitter.com/mikesherov/status/483713550964490240
https://github.com/InternetExplorer/Status.IE/commit/8522f67dd037453ac99f41ff5b4a7e66304bfbc5
