### ISSUE TITLE
Pointer Events W3C link points to wrong url

### ISSUE THREAD

**Issue by patrickhlauke** [MicrosoftEdge/Status#115]
http://status.modern.ie/pointerevents W3C button/link currently points to http://www.w3.org/html/wg/drafts/html/master/forms.html#attr-fe-inputmode - it should point to http://www.w3.org/TR/pointerevents/ (or dvcs.w3.org/hg/pointerevents/raw-file/tip/pointerEvents.html)

**Comment by domenic** [comment]
The latter, please—/TR/ links are always evil and outdated.

**Comment by jacobrossi** [comment]
Fixed @7d2b07f60f8929e8f1bcda4fcf4f6d34d7ff594f
