### ISSUE TITLE
When a long title is truncated, its tooltip doesn't show the full title

### ISSUE THREAD

**Issue by simevidas** [MicrosoftEdge/Status#119]
Example: http://status.modern.ie/mediaquerieslevel4interactionmediafeaturespointerandhover

![bt1io4lcyaa8uov](https://cloud.githubusercontent.com/assets/716405/3759213/66f50c18-1859-11e4-9120-e68ec3f17358.png)

(I had to inspect the DOM in the browser's DevTools to reveal the full title.)

**Comment by molant** [comment]
This applies to the (very) old website. Closing
