### ISSUE TITLE
Platform Status page fails to load in IE9

### ISSUE THREAD

**Issue by wiredprairie** [MicrosoftEdge/Status#122]
If you attempt to show the platform status page in IE9 (either stand-alone or in IE11 emulating IE9), the platform status page fails to show any status. The `Features found` is **0** and the list is blank. It works correctly in IE11 EDGE mode.

There are two errors in the console:

```
ReferenceError: 'requestAnimationFrame' is undefined <div class="filter-container" data-sticky="">
```

and

```
"Access is denied. ...
```

**Comment by dstorey** [comment]
The latter is probably due to CORS to fetch the data.

**Comment by jacobrossi** [comment]
Our analytics data shows fairly low traffic from IE9. So if you don't mind, I'm going to mark this Won't Fix. If you'd like to take a stab at fixing it though, feel free to submit a pull request.
