### ISSUE TITLE
Status: <picture> Element shipped in Firefox

### ISSUE THREAD

**Issue by scheinercc** [MicrosoftEdge/Status#123]
https://bugzilla.mozilla.org/show_bug.cgi?id=870022

**Comment by jacobrossi** [comment]
FF data for picture comes from the [Chromium Dashboard](https://github.com/GoogleChrome/chromium-dashboard/issues)

But in Aurora, I'm still getting undefined for HTMLPictureElement.

**Comment by jacobrossi** [comment]
This is still in development for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=870022#c117
