### ISSUE TITLE
CSS Filters - bugzilla link

### ISSUE THREAD

**Issue by scheinercc** [MicrosoftEdge/Status#124]
While this is still in development for Firefox this might be the right bug to link to:
https://bugzilla.mozilla.org/show_bug.cgi?id=869828

**Comment by jacobrossi** [comment]
Were you looking at a specific link in status.modern.IE that needs updating??  I don't think we have links to the individual bug trackers (good idea though, just not sure I've got the bandwidth to maintain them all)

**Comment by scheinercc** [comment]
Ah, forgot the link, right. It might have been this one: http://status.modern.ie/cssfilterimagefunction
- and regarding the bug links I guess that would only be maintainable if the other vendors or community provide them.

**Comment by jacobrossi** [comment]
For now I'm going to pass on including bug links given I don't have the bandwidth to go collect this for other in development features. Though feel free to submit a pull request! For CSS filters, I haven't seen any code patches start to show up for FF, so I don't think there's a status change to make here quite yet.  But when that does happen, the data for FF on this feature is coming from the Chromium Dashboard. https://github.com/GoogleChrome/chromium-dashboard

Reopen if I misunderstood the request. :-)
