### ISSUE TITLE
Request addition of progress and meter elements to feature list

### ISSUE THREAD

**Issue by tagawa** [MicrosoftEdge/Status#129]
These are bundled together in CanIUse but should be added as separate entities to the Status.IE feature list IMO, to clarify current IE support.

**Comment by dstorey** [comment]
Meter is tracked now: https://dev.modern.ie/platform/status/meterelement/
Progress has been supported for a long time prior to Edge, so isn't currently tracked

**Comment by tagawa** [comment]
Good stuff! Thanks @dstorey.
