### ISSUE TITLE
Add sometype of prerender for SEO

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/Status#13]
Maybe something like https://github.com/prerender/prerender?

**Comment by molant** [comment]
Working on this

**Comment by jacobrossi** [comment]
Bing recommendations: http://www.bing.com/blogs/site_blogs/b/webmaster/archive/2013/03/21/search-engine-optimization-best-practices-for-ajax-urls.aspx 

Alternative (less preferred) approach is crawlable ajax: https://developers.google.com/webmasters/ajax-crawling/

Let me know if you me to connect you with the Bing team on this.

**Comment by molant** [comment]
I'm afraid we need to create HTML snapshots. All the content is generated dynamically. I think I know how to make it work for Google with its escaped_fragment but I haven't found anything yet similar for Bing. Do you know anything?

Right now my approach is to use phantomjs to create a static html that will be deliver to the search engines. We only have one page so that should be manageable.

**Comment by dstorey** [comment]
I’m not a fan of the UA detection for crawlers as it isn’t future friendly, but I don't have a better suggestion right now. The static version would potentially give a better experience for some users though (those with no script, or potentially those with weaker hardware, mobile or whatever.) At the very minimum would there be a way to allow the user to override the sniffing and allow them to access that version, such as with a localStorage or cookie entry?  Maybe it doesn't have to be discoverable via the site itself, just there as an option if someone finds it.

Apart from that, would it be possible to move the UA detection out of the code into a config file or such? Might be nicer to have a JSON file or whatever that we can update as we discover UAs that would do better with the static version. For instance additional search engine bots, proxy based mobile browsers that don't handle the main site well, or whatever.

**Comment by molant** [comment]
I don't like neither the UA approach but the other solution is to generate all the HTML in the server side and that will be a massive rewrite of the current site. We will be storing also the data from chromestatus so...

The static page doesn't have any style so I'm not sure it will be useful to serve it to anything other than a bot...

I'll move the UA to a config file!
