### ISSUE TITLE
WebDriver available in IE 11

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#134]
I think [1] and [2] indicate that WebDriver is already available in IE 11. So do we need to update the status here http://status.modern.ie/webdriver ?

[1] http://msdn.microsoft.com/en-us/library/ie/dn800898(v=vs.85).aspx
[2] http://support.microsoft.com/kb/2990999

**Comment by jacobrossi** [comment]
Indeed! Fixed with https://github.com/InternetExplorer/Status.IE/commit/a1c6c807deb95c9f39c53eb55d525df5e9d1d96a
