### ISSUE TITLE
README should mention Chromestatus data source

### ISSUE THREAD

**Issue by ebidel** [MicrosoftEdge/Status#135]
If people want to file bugs against the data, it would be good to capture those reports: https://github.com/GoogleChrome/chromium-dashboard

**Comment by molant** [comment]
It is explained in
https://github.com/InternetExplorer/Status.IE/blob/production/CONTRIBUTING.md
but I guess we can put it in the README.md too :)

**Comment by ebidel** [comment]
That seems fine, although I didn't think to look there :)

**Comment by jacobrossi** [comment]
Seems reasonable to point it out as I've had to redirect a number of issues to the Chromium Dashboard that were erroneously filed on this repo.  I've updated the readme and I'll continue to redirect any data issues we hear about. Thanks @ebidel

**Comment by ebidel** [comment]
Awesome!
