### ISSUE TITLE
Feature Request: Provide ETA for features that are in development

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#137]
There are currently 32 features in development and one feature released in IE Developer Channel. It would be helpful if we can know when these features will be released and whether they will be added to current version of IE, like WebDriver and WebGL Instancing Extension, or introduced in future releases (and which one).

**Comment by jacobrossi** [comment]
Definitely understand the request! It's generally hard to commit to ETAs in advance and exposing our current guess would end up being far too noisy with changes (which would inevitably make people mad).  I'll keep this one in mind if I can find a way that balances the commitment people expect from status announcements with the valuable transparency ETAs would provide.
