### ISSUE TITLE
Redirect was blocked for CORS request. Should use HTTPS

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#140]
Now http://www.chromestatus.com redirects to https://www.chromestatus.com, but status.ie still uses http. So now the CORS is blocked by IE since http://www.chromestatus.com doesn't send a "allow cors" header, and thus the page cannot show up anything now. Please change the Chrome status URL to use https and make a http to https redirect on status.ie as well.

**Comment by molant** [comment]
http request switched to https in fd89e2b5842e482cf2f13d44bc1d5945e09f77fb
Going to work on https only now.
