### ISSUE TITLE
IE Logo is wrong opacity for Preview Release

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#145]
The logo to show IE support for features in the preview release is almost fully transparent. It should be at least as opaque as in development, if not more so.

**Comment by jacobrossi** [comment]
Yeah, same opacity as in development sounds appropriate.

-----Original Message-----

**Comment by jacobrossi** [comment]
Fixed with https://github.com/InternetExplorer/Status.IE/commit/4762f37534848f81035811ddcb32bc1e54f66366
