### ISSUE TITLE
Track support for CSS "all" shorthand

### ISSUE THREAD

**Issue by charlesjmorris** [MicrosoftEdge/Status#147]
http://dev.w3.org/csswg/css-cascade/#all-shorthan

https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6511510-all-initial

**Comment by dstorey** [comment]
Should this just track `all` or also the [CSS-wide defaulting keywords](http://dev.w3.org/csswg/css-cascade/#defaulting-keywords)?

We don’t support `initial` (supported by Chrome, Firefox, Safari, and Opera) or the `unset` keyword (Firefox only).

**Comment by dstorey** [comment]
Fixed with recent updates
