### ISSUE TITLE
Question: Why not XPath Level 2?

### ISSUE THREAD

**Issue by am11** [MicrosoftEdge/Status#152]
@dstorey, according to https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6512573-xpath-2-and-3, XPath 3 is under development. Does this mean you guys are bypassing / don't-need XPath L2? Conversely, does XPath L3 offsets L2? If not, please add L2 in your bucket list.

Nonetheless, thanks for considering it. :+1: 

Hopefully, other teams will pick it up too: as a SharePoint dev, I would love to configure my CQWP with XPath L2 / L3 and PowerShell might be able to take advantage of it as well. (-8

**Comment by jacobrossi** [comment]
XPath L3 is a superset of L2. [Here's the list](http://www.w3.org/TR/xpath-30/#id-revision-log) of what was added in L3. So we should have your request covered. :-)  Thanks for the feedback!

**Comment by am11** [comment]
Thanks! :+1:
