### ISSUE TITLE
Support for Encoding API & TLS 1.3?

### ISSUE THREAD

**Issue by ashumeow** [MicrosoftEdge/Status#156]
After viewing IE status [https://status.modern.ie]
I couldn't find support for Encoding API [https://encoding.spec.whatwg.org/]
Ref--- https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6558040-support-the-encoding-api
Also, TLS 1.3 support is there in HTTP/2.0. So, if you guys are providing HTTP/2 power for modern IE, then why am i seeing TLS 1.2 in the IE status page? [https://status.modern.ie/tls12]
TLS 1.3 [http://tools.ietf.org/html/draft-ietf-tls-tls13-02]
[https://github.com/tlswg/tls13-spec]

**Comment by cemerick** [comment]
Why close now? Is there a rev of IE that includes the Encoding API?

**Comment by ashumeow** [comment]
Do i look like the person who work there? I'm sure that they will never consider from stupids or losers. I am closing all issues and silly pull requests which i sent to some repos, sorry (^_^)

**Comment by cemerick** [comment]
@ashumeow Wasn't implying you were responsible.

**Comment by molant** [comment]
In [contributing.md](https://github.com/InternetExplorer/Status.IE/blob/production/CONTRIBUTING.md) you can see the main source of information comes from the chromium dashboard and it is preferable to add new features there. If they are indeed already tacked, then please open an individual ticket for each one with the right ID.

Thanks!

**Comment by ashumeow** [comment]
That's why i closed the issue. I can discuss with Googly Booglies instead lol #Kidding

#EndOfStory

**Comment by jacobrossi** [comment]
I don't think this a silly issue in the least. Tracking the Encoding API on this site makes total sense.  I need to chat with our team that owns this and see where it's at in our roadmap. But it certainly should get a mention on status. 

Tracking it upstream in the Chromium dashboard is preferable from a maintenance standpoint, but we have plenty of features that started on our dashboard first. So I don't think that's a blocker.

**Comment by ashumeow** [comment]
May i know the progress of this feature thing? Just curious to know. =)

**Comment by saschanaz** [comment]
The Encoding thing is here: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/encodingstandard/?q=encoding

Still no TLS 1.3 item.

**Comment by saschanaz** [comment]
TLS 1.3 is added by #517 :smile:
