### ISSUE TITLE
Create readme

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#16]
Before v1 release we should add a readme that explains the steps to set up the environment and run the code, etc.

**Comment by molant** [comment]
@jacobrossi what sections do you want it to have?
Probably we need something like:
- What is this project
- How to install it and run it
- How to submit code
- License

Something else?
Can you help with the copy for some of these sections (1 and 3 probably)

**Comment by molant** [comment]
We have the readme file so closing this. @jacobrossi if there is something missing please reopen it again.
