### ISSUE TITLE
Feature: Add hash links

### ISSUE THREAD

**Issue by am11** [MicrosoftEdge/Status#161]
Please add hash-link pin for each feature, so we don't need to get the id from DOM selector to make the internal link.

Something like ([WE website](http://vswebessentials.com/features/bundling)):

![internal-link](https://cloud.githubusercontent.com/assets/3840695/5068706/faf12b62-6e59-11e4-823e-a975bd660b60.png)

Note: it doesn't copy the URL to the clipboard, but just navigate to the internal link and display it in address-bar, so user can bookmark or copy it for sharing.

Thanks.

**Comment by molant** [comment]
Hello @am11 

If you expand a feature the url will be changed to that one and you can use that link to share. For example, click on https://status.modern.ie/customelements and wait a few seconds until all the content has been loaded, the page should scroll to custom elements and have that feature expanded.

If this feature is not working for you let us know what browser and version you are using.

Thanks!

**Comment by am11** [comment]
Oh just realized, it's working as you have described. :)
Thanks!
