### ISSUE TITLE
Input date-time related types

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#163]
IE lacks support for input types date, time, month, datetime, datetimelocal and week.

`input [type=url]` is also not supported (it doesn't validate).

There is no info about missing input types on ie-status website.

Here is a list of input types which Chrome supports: http://www.w3.org/TR/html-markup/Overview.html#input.time-toc. Obviously Chrome supports everything and have best HTML5 features coverage! I wonder, what is stopping IE guys to go after the winner and go wild with the pending features? Instead of spending time on dressing up new releases dramatically, which are tied to _only latest version of OS_ anyway! (or busy closing bug reports with `By Design` status, eh?). Enough with the bureaucracies, procrastinations and the "We don't think it is required for our next release" attitude. Well you don't get to decide that! Web is for everyone, we need ALL standards support equally! At least, give this BS a pause for couple of months, put your game face on, implement EVERYTHING remaining, release on all active versions of Windows, release bug fixes as per our feedback and then resume back to normal lazy drama routine: wasting time with marketing folks.
or just..
GO OPEN-SOURCE IE and GO WILD! Make web a better place for mankind.

**Comment by dstorey** [comment]
Beyond the HTML5 input types feedback for StatusIE, you can vote for features you want implemented at [uservoice.modern.ie](http://uservoice.modern.ie). We're responding to feedback there. We've also been improving the Connect experience. The statuses didn't always mean what they seemed like from the outside.

**Comment by ghost** [comment]
input date, time: https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6513996--input-type-date-input-type-time

input color: https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6514216--input-type-color

**Comment by jacobrossi** [comment]
Looks like #38 . I'm going to get these added soon.

**Comment by jacobrossi** [comment]
Marking duplicate since #38 covers this. Thanks for reminding me!
