### ISSUE TITLE
Screen Orientation API: Chrome is current

### ISSUE THREAD

**Issue by tomByrer** [MicrosoftEdge/Status#165]
https://status.modern.ie/screenorientationapi
http://caniuse.com/#feat=screen-orientation

**Comment by tomByrer** [comment]
Thanks, but Chrome support doesn't seem to be updated on the live website?  Is the build more occasional?

**Comment by jacobrossi** [comment]
Should be deployed now (it first deploys to a staging server for testing). Thanks!

-----Original Message-----

**Comment by tomByrer** [comment]
:+1: :cake:
