### ISSUE TITLE
Merge features.json & ie-status.json please

### ISSUE THREAD

**Issue by tomByrer** [MicrosoftEdge/Status#166]
The current split item names in one JSON & browser compatibility chart in another is a mess & prevents those who want to write PRs to help you guys.

**Comment by molant** [comment]
The features.json you are seeing in the code is just a place holder. On runtime we are using the one coming from [chromestatus](https://www.chromestatus.com/features.json) and we add our IE specific information on top of it.
So if there is information wrong about any browsers that is not IE you will have to do a PR in the chromestatus project and if it is IE, in ours.

Thanks!
