### ISSUE TITLE
Back navigation issues

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/Status#17]
There have been some complains about the back navigation not behaving as expected when browsing several features.
We should investigate this.

**Comment by jacobrossi** [comment]
Yeah, I saw that on Twitter. When I tried it earlier, I saw the back button updating the URL yo different features I had clicked, but the page was not scrolling to those features (e.g. Only the URL was changing).

-----Original Message-----

**Comment by molant** [comment]
Working on this
