### ISSUE TITLE
Update URL API link and status

### ISSUE THREAD

**Issue by rubys** [MicrosoftEdge/Status#173]
From production/app/static/ie-status.json:

```
 {
"name": "URL API",
"category": "DOM",
"link": "https://dvcs.w3.org/hg/url/raw-file/tip/Overview.html",
"summary": "Expose constructible URL objects that can be manipulated and combined.",
"standardStatus": "Established standard",
```

The link is no longer active (it redirects).  Consider updating it.  Candidates:
- https://url.spec.whatwg.org/
- https://specs.webplatform.org/url/webspecs/develop/
- http://www.w3.org/TR/url/

Additionally, the standardStatus is incorrect.  I'd suggest "Editor's draft" instead.

**Comment by ghost** [comment]
I suggest using https://url.spec.whatwg.org/, as this is where the original link redirects to.
