### ISSUE TITLE
Add WebGL 2 support

### ISSUE THREAD

**Issue by AshleyScirra** [MicrosoftEdge/Status#188]
IE11 already supports WebGL, but it would be nice if status.modern.ie could also show the status of WebGL 2 as well. Currently there's no item there so we have no idea if it's not currently planned/considered/in development etc.

**Comment by benaadams** [comment]
https://www.chromestatus.com/feature/6694359164518400
![webgl2](https://cloud.githubusercontent.com/assets/1142958/6970629/95c318ce-d96e-11e4-98b9-3db5cbb15fde.PNG)

https://twitter.com/Tojiro/status/583686243046723586
![ctweet](https://cloud.githubusercontent.com/assets/1142958/6970639/a57b7ad6-d96e-11e4-9dd2-53cf86fa8437.PNG)

https://blog.mozilla.org/futurereleases/2015/03/03/an-early-look-at-webgl-2/
![ff](https://cloud.githubusercontent.com/assets/1142958/6970642/ad2423a0-d96e-11e4-8da8-a158075efd0c.PNG)

https://twitter.com/LostOracle/status/559835205129629697
![fftweet](https://cloud.githubusercontent.com/assets/1142958/6970644/b309e67e-d96e-11e4-9a78-2bcfa1e285f1.PNG)
