### ISSUE TITLE
Improve PNG minification

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/Status#19]
@dstorey has managed to reduce the size of the individual images and the sprite a lot. I've tried to use the option pngquant of grunt-contrib-imagemin and reduced the size of the sprite to about 10KB but sometimes the process fails.
The associated issue is https://github.com/gruntjs/grunt-contrib-imagemin/issues/189

Right now we are minifying all the images. Maybe we can just reduce the sprite file? @dstorey, are we using any other images outside the sprite?

**Comment by dstorey** [comment]
The manual compression was done by using a mixture of pngquant and pngnq and various colour depths, depending on the image. The more complex images (browser icons) preferred pngquant and needed a higher number of colours, while the single or duel colour icons mostly reduced better using pngnq and between 4–8 colours. I also used ImageOptim on the resultant file (can be automatically applied using the ImageAlpha tool I used to reduce the colour depth.) The generated sprite sheet from those compressed images is around 7.1k after ImageOptim  and 8k before. That had best results using pngquant and 256 colours. Could be potentially decreased to 6.7k before optim with 128 colours and a little loss in detail.

@molant currently we have one image outside the sprite (the IE logo in the header, which is applied using ::before so didn't work well with the auto generated sprite.) I could potentially turn that into a SVG  and include it in a SVG sprite if we have a source vector version somewhere. There is also a twitter logo outside the sprite, but that is currently a font and should probably be moved into the sprite, as (I think?) we're only using that font for that one icon.

**Comment by dstorey** [comment]
We can potentially move the category icons outside the sprite and into an SVG sprite using [these images](http://www.w3.org/html/logo/#downloads), but we need to evaluate the size/performance trade off. Not sure if we currently compress our SVG files. The Safari tools say not.

**Comment by molant** [comment]
We are minifying the svgs with svgmin but we are not creating any sprite at the moment.

I guess svg will be better for scaling to different resolutions. We can look into that.

With pngquant the final spritesheet is 10kb which is still better than what we have right now. I think that in the meantime I'm going to compress just that image and the IE logo while we investigate svg. Sounds good?

-----Original Message-----

**Comment by dstorey** [comment]
works for me

**Comment by molant** [comment]
So pngquant is not working property in Azure Websites. It generates a broken png with missing images. I've tried changing the parameters of grunt-contrib-imagemin but haven't been successful. Of course, it works on my machine (tm) so I've disabled it for now until we figure out what is going on.

**Comment by molant** [comment]
Not fixed, pngquant doesn't work yet

**Comment by molant** [comment]
With version 0.7.0 and pngquant the spritesheet size is 20KB smaller!
