### ISSUE TITLE
Apply a content security policy header

### ISSUE THREAD

**Issue by david-risney** [MicrosoftEdge/Status#192]
As web site that's heavy on client side JavaScript, promoting web standards, and given that the Win10 preview includes a CSP implementation, how about applying content security policy headers?

**Comment by molant** [comment]
Good idea,

I've played a bit with [Helmet](https://github.com/helmetjs/helmet) but I'm having some issues getting the reporting to work on Chrome (the report url gets notified, but there isn't any information). Have you tried it? Any other module that you suggest for CSP?

**Comment by david-risney** [comment]
I have a PR https://github.com/InternetExplorer/Status.IE/pull/193 in which I just apply the header. I used the https://github.com/david-risney/CSP-Fiddler-Extension (a tool I made for this purpose) to find the correct policy. I don't know of a good module to help with this =)

**Comment by jacobrossi** [comment]
Migrating this to our repo for dev.microsoftedge.com
