### ISSUE TITLE
web idl?????

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#198]
Me: cortana, what the heck is Web IDL?
Bing (on behalf of cortana):

![webidl](https://cloud.githubusercontent.com/assets/2031765/6556700/ec85a384-c677-11e4-9d68-5d95bda60f58.PNG)

Looking at the status.IE, It seems like IE team like me is clueless about this technology.

**Comment by adrianba** [comment]
WebIDL is used by just about every item on the status.IE list. It is primarily a spec that defines an IDL used by other specs. Please can you be more specific about what you think is missing?

**Comment by ghost** [comment]
Sorry for the buzz. I just read this answer: http://stackoverflow.com/a/21736543/1712065 and the comments that goes with it. :)
