### ISSUE TITLE
Add button butts against filter field in production, but not locally

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#20]
We set the filter field and button as inline-block. Inline blocks render the white space (well one character’s worth) between elements. In production we remove any whitespace in the HTML, so the space goes away.

Two Solutions: 
- add margin (potentially different spacing in production and live)
- change to float, flexbox or other

**Comment by dstorey** [comment]
Will fix this as part of #18 changes.

**Comment by jacobrossi** [comment]
Should this be closed now?

**Comment by dstorey** [comment]
Once my latest branch goes from dev to production it should close, along with a couple of other bugs I opened.
