### ISSUE TITLE
Add "Upgrade Insecure Requests" to the dashboard.

### ISSUE THREAD

**Issue by mikewest** [MicrosoftEdge/Status#202]
Spec: https://w3c.github.io/webappsec/specs/upgrade/

> This document defines a mechanism which allows authors to instruct a user agent to upgrade _a priori_ insecure resource requests to secure transport before fetching them.

We're planning on shipping this in Chrome 43ish.

Intent to Ship: https://groups.google.com/a/chromium.org/d/msg/blink-dev/BDHLrC8UM-Y/amTCDlWJnk8J

It would be lovely if Microsoft would take a close look at the spec, as we (and the EFF) believe it's going to be a nice way of getting one big issue out of the way for sites that wish to upgrade to HTTPS sooner rather than later.

**Comment by molant** [comment]
The id in chromestatus seems to be `6534575509471232`.

**Comment by mikewest** [comment]
Correct: https://www.chromestatus.com/features/6534575509471232. Sorry, I should have linked that.

**Comment by molant** [comment]
No worries, I just look into the json file. We are merging with the content from chromestatus so we just need to keep track of IE/Spartan.

Thanks!

**Comment by ghost** [comment]
User voice: https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/7314353-upgrade-insecure-requests
