### ISSUE TITLE
Filter field loses focus after adding a tag in IE

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#22]
Steps:
1. Click on filter field
2. type a term and press enter

Expected

In Chrome/Safari/Firefox/Presto-Opera the focus remains in the filter field so you can enter a new tag without clicking inside the field again

Actual:

In IE (tested IE11 so far) the filter field loses focus.

**Comment by jacobrossi** [comment]
Looks like an IE bug. 😞  I'll get it filed internally. Work around is to call focus on the input during the submit event.

-----Original Message-----

**Comment by dstorey** [comment]
@molant something you can fix?
