### ISSUE TITLE
SVG: Text can't be aligned vertically

### ISSUE THREAD

**Issue by ashelley** [MicrosoftEdge/Status#221]
I just ran across this problem and it seems to be an old one.  Not sure if this is the right place to post this but I wanted to bring attention to this issue:

https://connect.microsoft.com/IE/feedback/details/801719

The problem is that IE11 (tested 11.0.9600.17690) still doesn't support alignment-baseline or dominant-baseline on text nodes.

**Comment by HolgerJeromin** [comment]
This is/was a problem for Presto (Opera v12), too. My solution is

```
if (verAlignment == "middle"){
  VisualObject.setAttribute("dy", "0.6ex");
}else if (verAlignment == "hanging"){
  VisualObject.setAttribute("dy", "1ex");
}
```

But i would be happy if this ancient problem would be solved...

**Comment by jacobrossi** [comment]
Hi @ashelley - this isn't the right place to file bug reports or feature suggestions. Connect is a good place to file this. You might also post to http://uservoice.modern.ie and solicit votes.  Thanks!

**Comment by HolgerJeromin** [comment]
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/7887774-support-dominant-baseline-in-text-element-in-svg waits for votes :-)

**Comment by ashelley** [comment]
thanks @jacobrossi I tried to find the right place... appreciate you pointing me in the right direction.  @HolgerJeromin +1'd
