### ISSUE TITLE
Incorporate WebKit Status Data

### ISSUE THREAD

**Issue by phistuck** [MicrosoftEdge/Status#223]
WebKit has started publishing its status data as well -
http://www.webkit.org/status.html
Which seems to come from -
https://svn.webkit.org/repository/webkit/trunk/Source/JavaScriptCore/features.json
And -
https://svn.webkit.org/repository/webkit/trunk/Source/WebCore/features.json

This should be incorporated, like the Chrome and Opera status data.

Note that this will have to rely on feature names, unfortunately. They have not specified numeric IDs of any sort. Perhaps this could get away with WebKit Bugzilla bug IDs, but not all of them has one, so names (which are used for the anchors, too) are the only reliable choice, I guess.

I plan to work on it this week, unless someone is very eager to do it now.

**Comment by molant** [comment]
Cool!
@phistuck right now we are pulling all the information for other browsers from chromestatus. We are a bit buried with [//BUILD/](http://www.buildwindows.com/) this week and the [Project Spartan Summit](http://devchannel.modern.ie/websummit2015) next one to see how this should be implemented but should have more time after in case you want to wait on implementing this.

**Comment by phistuck** [comment]
I was thinking to get the data from the WebKit status data and fallback to the Chrome status when it is missing.

**Comment by jacobrossi** [comment]
Closing per Apple's unfortunate comment that they don't publish Safari status data.
https://github.com/MicrosoftEdge/Status/pull/226#issuecomment-97672727
