### ISSUE TITLE
Add a little link to each individual features

### ISSUE THREAD

**Issue by FremyCompany** [MicrosoftEdge/Status#227]
(rough draft of what it could look like)

A bit of html in the feature.html template:

```
 <a class="web-feature-link" href="#conditionalrules">§</a>
```

Some magic css:

```
.web-feature-link {
    position: absolute; display: none;
    left: -20px; top: 0%; width: 16px; height: 50px;
    padding: 12px 4px; font-size: 15pt; 
    background: rgb(250, 250, 250); 
}
.web-feature:hover > .web-feature-link {
    display: block;
}
```

And some script

```
 window.onhashchange = function() {
    // expand the division 
    // scrollIntoView its bottom
    // scrollIntoView its top
}
```

**Comment by jacobrossi** [comment]
yeah we thought about this (err, I was outvoted :-) ), but instead just went with updating the URL when you expand it (which you can then copy from the address bar).  we're trying to keep the content of the feature box as clean as possible at this point.

**Comment by dstorey** [comment]
If we ever do this, it is important to have correct link text. In the e.g. above it would read out the section sign. In that case adding an aria-label would solve the issue.
