### ISSUE TITLE
Browser Status Icons are difficult to understand

### ISSUE THREAD

**Issue by nkronlage** [MicrosoftEdge/Status#235]
Maybe it's my monitor or my vision, but trying to tell the difference between some of the status icons for the various browsers is very difficult.  I.e., is this icon slightly grayed out or not?  

A tool tip or text below the icon would really help out here.

**Comment by molant** [comment]
There is already a tool tip:
![image](https://cloud.githubusercontent.com/assets/606594/7904976/07307ce4-07c4-11e5-811d-bad5e26f4276.png)

Also we are changing the design at the moment and we will take into account your feedback. You can change a new version (not final yet) in http://dev.modern.ie/platform/status/
