### ISSUE TITLE
Edge and IE status text should be separated

### ISSUE THREAD

**Issue by charlesjmorris** [MicrosoftEdge/Status#242]
Right now, the tooltip text for IE and Edge icons in each feature is the same. They should be separated since new features are not being considered or put in preview for IE.

https://twitter.com/m_gol/status/618191628906446848

**Comment by jacobrossi** [comment]
:+1: nice find. Looking at this today.

**Comment by mgol** [comment]
I should have reported it here instead of on Twitter. :-) I'll remember in the future.

**Comment by jacobrossi** [comment]
No worries, just thanks for reporting it.  I fixed this just now (UI code for dev.modern.ie is in another repo)
