### ISSUE TITLE
Safari supports showModalDialog

### ISSUE THREAD

**Issue by mgol** [MicrosoftEdge/Status#247]
Safari 8 does support `showModalDialog`, the example:
http://samples.msdn.microsoft.com/workshop/samples/author/dhtml/refs/showModalDialog.htm
works. And yet the status page claims it's not implemented in Safari.

**Comment by domenic** [comment]
In general the status page is pretty confusing on this. "Deprecated" in my mind means "still works but you shouldn't use it." Which is true in Firefox, but in Chrome and Edge it's totally removed.

**Comment by jacobrossi** [comment]
Yeah, we need a "removed" status.  Just haven't had time to implement it yet.

**Comment by mgol** [comment]
Before the "removed" status is implemented at least the Safari status can be changed to "supported".

**Comment by dstorey** [comment]
There is no field for Safari in our showModalDialog section, so it pulls the data from ChromeStatus. @jacobrossi am I right, or because we have a Firefox override, does it not pull in for the others too?

**Comment by domenic** [comment]
Mobile Safari does not support showModalDialog, fyi.

**Comment by molant** [comment]
We are pulling the data from chromestatus.
If the data for Safari is incorrect please open an issue in the [Chromium dashboard](https://github.com/GoogleChrome/chromium-dashboard/issues)
