### ISSUE TITLE
Add Screen Capture API

### ISSUE THREAD

**Issue by jacobrossi** [MicrosoftEdge/Status#248]
Screen Capture
http://w3c.github.io/mediacapture-screen-share/
Screen Capture API allows a user's display or parts thereof be used as the source of a media stream.

FF: in development
Chrome: not supported
Safari: not supported
Edge: under consideration

**Comment by dstorey** [comment]
Screen capture is already on the site https://developer.microsoft.com/en-us/microsoft-edge/platform/status/screencapture
