### ISSUE TITLE
Status shows released features in "Preview Release"

### ISSUE THREAD

**Issue by Studio384** [MicrosoftEdge/Status#249]
The status site hasn't been updated yet since the launch of Windows 10 and Edge and still claims features that are supported are in a Preview Release.

**Comment by jacobrossi** [comment]
Thanks, we have some major updates in testing that will address this and other issues.

**Comment by jacobrossi** [comment]
These changes rolled out today. It shows features "Supported" (shipped in build 10240), "Preview" (features not yet on by default in a stable release), and what preview features are behind flags.  Check it out and let me know if you see issues.

**Comment by Studio384** [comment]
No issues, but I did notice that Firefox can't load all category icons. Device, DOM, Misc, Network / Connectivity, Offline / Storage, Realtime / Communication, Security, Web Components and File API don't have an icon, but I'll open another ticket for that.
