### ISSUE TITLE
HTML5 Audio Ogg/Opus formats

### ISSUE THREAD

**Issue by ericlaw1979** [MicrosoftEdge/Status#250]
https://twitter.com/ericlaw/status/457184317785907201

**Comment by dstorey** [comment]
userVoice: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6513488-ogg-vorbis-and-opus-audio-formats-support-firefox
CanIUse: http://caniuse.com/#feat=opus
ChromeStatus: https://www.chromestatus.com/features/4891189287321600

**Comment by jacobrossi** [comment]
Done:

http://dev.modern.ie/platform/status/opusaudiocodec/
http://dev.modern.ie/platform/status/vorbisaudiocodec
http://dev.modern.ie/platform/status/oggcontainer
