### ISSUE TITLE
Reading View Destroys MathJax rendering

### ISSUE THREAD

**Issue by arebee** [MicrosoftEdge/Status#252]
In Edge compare the MathJax content in 
http://leancrew.com/all-this/2015/08/satellite-of-love/ with `read:http://leancrew.com/all-this/2015/08/satellite-of-love/`

Specifically search for F
=G
M
mr2=mv2r=ma

**Comment by jacobrossi** [comment]
Thanks! This isn't the right place to file bugs for Edge, however. Please file this at http://connect.microsoft.com/ie

**Comment by arebee** [comment]
@jacobrossi Hey - that's a pretty poorly named URL for Edge bugs...
https://connect.microsoft.com/IE/feedback/details/1644857 created.

**Comment by jacobrossi** [comment]
Yep, we have plans to build something entirely new. This is for the time being.
