### ISSUE TITLE
Add backdrop-filter to the feature list

### ISSUE THREAD

**Issue by chaoaretasty** [MicrosoftEdge/Status#253]
This is from FilterEffects Module Level 2, currently implemented in Safari 9, there are also issues raised against both [Chrome](https://code.google.com/p/chromium/issues/detail?id=497522) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1178765) for this feature.

**Comment by dstorey** [comment]
userVoice: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/9160189-backdrop-filters
