### ISSUE TITLE
Category icons don't show up in Firefox

### ISSUE THREAD

**Issue by Studio384** [MicrosoftEdge/Status#255]
In Firefox, the icons for the categories Device, DOM, Misc, Network / Connectivity, Offline / Storage, Realtime / Communication, Security, Web Components and File API aren't shown.
![knipsel](https://cloud.githubusercontent.com/assets/1693592/9315718/16911720-4531-11e5-84dd-b67b8be9cf4a.PNG)

**Comment by molant** [comment]
Renders fine on my machine with FF. Can you try clearing the cache see if that fixes?

**Comment by Studio384** [comment]
Whoops, never mind. :)
