### ISSUE TITLE
Add "Content Security Policy Level 2"

### ISSUE THREAD

**Issue by mikewest** [MicrosoftEdge/Status#260]
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/9163354-content-security-policy-level-2
https://www.chromestatus.com/features/4957003285790720

Shipping in Chrome since ~38ish? Mozilla has a partial implementation.

Thanks!

**Comment by dstorey** [comment]
Need to double check the priority level with the team, then I'll add a CSPL2 entry. Will likely keep current CSP entry as is without adding Level 1 to the title so that existing links don't break.
