### ISSUE TITLE
Job to automatically change userVoice status when Status status changes 

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#261]
Currently it is a manual process to update userVoce when the status on Status changes. We have the userVoice ID in the status entry already, so we should be able to do a job to update the status there when an update is pushed.

Most of the status here map. Under Consideration High and Medium should map to On the Backlog, with a note about the priority.

**Comment by molant** [comment]
Can you add it to a trello card in the user stories please?

**Comment by codepo8** [comment]
It would be great to automate that the other way around, too. See https://twitter.com/LeaVerou/status/638653401891520512

**Comment by gregwhitworth** [comment]
It also would be good, if possible, to make the categories the same so that we, and more importantly the devs, aren't having to remember what two different types of categories mean.

**Comment by jacobrossi** [comment]
Migrating to EdgePortal issue...
