### ISSUE TITLE
The redirect breaks the JSON file (status.modern.IE/features)

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#264]
https://status.modern.IE/features no longer returns a JSON. Instead it redirects to https://dev.modern.ie/platform/status/features/, which is a HTML.

**Comment by ghost** [comment]
https://github.com/MicrosoftEdge/Status/blob/production/web.config#L20: The StatusRedirect should exclude /features, /uservoice, and /favicon.ico.

**Comment by molant** [comment]
@nextPrime why should we exclude favicon.ico from the list?
In the meantime we have http://dev.modern.ie/api/platform/status/

@jacobrossi I think we should redirect the old endpoint to this one. What do you think? About uservoice I think it is already integrated in it.

Thanks for reporting this!

**Comment by ghost** [comment]
@molant I think it's fine not to exclude favicon.ico, since it won't be requested any more. I wrote favicon.ico along with features and uservoice, because I saw it in  https://github.com/MicrosoftEdge/Status/blob/production/app.js#L38.

**Comment by ghost** [comment]
Thanks for the new link! The document readme.md needs to update too.

**Comment by molant** [comment]
Updated the readme.md. @kypflug, @jacobrossi can one of you update the web.config?

**Comment by ghost** [comment]
@molant By the way, https://dev.modern.ie/api/platform/status/ doesn't send Access-Control-Allow-Origin header.

**Comment by molant** [comment]
:_(

**Comment by jacobrossi** [comment]
This should be fixed now.
