### ISSUE TITLE
Fetch is incorrectly marked in Firefox & Opera as "In Development"

### ISSUE THREAD

**Issue by mgol** [MicrosoftEdge/Status#265]
Chrome, Firefox & Opera all support the fetch standard. Firefox had some problems before v40 but they should be resolved now.

Source: http://caniuse.com/#search=fetch

**Comment by molant** [comment]
@mzgol the information for other browsers comes from [chromestatus](https://www.chromestatus.com/features/6730533392351232).
We only take care of the [IE/MSEdge part](https://github.com/MicrosoftEdge/Status/blob/production/CONTRIBUTING.md#updating-features) :)
Please file a bug with them and it will get fixed automatically in here.

Thanks!

**Comment by mgol** [comment]
Ah, ok. I thought only Chrome data is taken from there. :)

**Comment by mgol** [comment]
Hmm, the page you linked to claims Firefox supports the API and Opera has supported it since version 29. So it seems chromestatus already has correct data.

EDIT: Firefox has a green dot but is marked as "in development", that confused me. However, Opera has the "Enabled by default" tooltip so that part should be ok?

**Comment by molant** [comment]
The issue then could be that we are not loading the latest chrome features updated (we had to change it recently). I'll open a new bug in the dev.modern.ie issue tracker to fix it.

Thanks!
