### ISSUE TITLE
Track CSS L4 conic-gradient()

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#272]
One of top trending userVoice suggestions: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/8471413-implement-conic-gradients-from-css-image-values-le

Spec: http://www.w3.org/TR/css4-images/#conic-gradients

**Comment by LeaVerou** [comment]
Please look at [the ED](http://dev.w3.org/csswg/css-images-4/#conic-gradients) instead, as I've added several examples as well as a rotation angle argument. 

Btw given that Direct2D 1.1 supports mesh gradients, Edge can implement this more easily than any other UA, as you guys don't have to worry about shitty Core Graphics on OSX.
