### ISSUE TITLE
Discrepancy between status and uservoice

### ISSUE THREAD

**Issue by codepo8** [MicrosoftEdge/Status#275]
Just got this complaint:

.@MSEdgeDev Why are conic gradients not on https://dev.modern.ie/platform/status/css/ … even though they’re marked as “Under Review” on https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/8471413-implement-conic-gradients-from-css-image-values-le … ?

Is this a manual process? If so, can we automate that somehow?

**Comment by dstorey** [comment]
@codepo8 We sat as a team and went through the userVoice items we had updates for. I created bugs here for any popular suggestions we didn't track on status more or less right after, but they can't just be added to Status right away (or automatically) as we need to write a blurb explaining feature, research browser support, etc. Anyone can create a pull request to add issues on Status though. We‘d then need to review it to makes sure it is correct, and to set the correct priority.

**Comment by dstorey** [comment]
Should be solved for the most part.
