### ISSUE TITLE
No link to this repo on status.modern.ie

### ISSUE THREAD

**Issue by codepo8** [MicrosoftEdge/Status#276]
Is that by design? Would be useful to get real issues filed rather than people complaining on Twitter.

**Comment by dstorey** [comment]
@codepo8 it was included in the previous site. We‘re still moving over to the new site and design, etc. Need to check to see if that is part of the current work in progress.

**Comment by melanierichards** [comment]
GOOD. POINT.

I can add a Github button to the header of Status linking to this repo. Will do this independently of other open Status work so it can get merged in sooner. @jacobrossi do you have any reservations with this?

**Comment by dstorey** [comment]
This is included now
