### ISSUE TITLE
mjpg support seems dubious

### ISSUE THREAD

**Issue by patrickkettner** [MicrosoftEdge/Status#287]
MJPG is listed as shipped, however I am unable to find any stream in which is actually works. Can anyone?

**Comment by patrickkettner** [comment]
[several](http://141.89.114.98/demo/edu640x480v.html) [demos](http://www.snowtrails.com/cam_files/all_cams.php?port=10197)

**Comment by jacobrossi** [comment]
I think we have bugs tracking the ones that don't work above. This is supported though!
