### ISSUE TITLE
any plans to add css "appearance" property support?

### ISSUE THREAD

**Issue by michaelwarren1106** [MicrosoftEdge/Status#289]
I know its not in any spec, but there's a -webkit prefixed version available for taking away the default appearance of select boxes in webkit browsers.

I checked the modern.ie roadmap, and didnt see any mention of "appearance" in there, but its definitely a common desire to have custom styled form elements and selects, radios, and checkboxes have always been the trickiest.

Any plans to support the "appearance" property, either prefixed or no?

**Comment by jacobrossi** [comment]
Microsoft Edge already supports -webkit-appearance. But it might be difficult in status to report on the interoperability given there is no spec for this. @dstorey wdyt?

**Comment by molant** [comment]
FYI, there is a list of all the CSS properties we support in https://dev.modern.ie/platform/documentation/apireference/cssstyles/. I believe we had somewhere the webkit ones in another place as well.

**Comment by michaelwarren1106** [comment]
http://caniuse.com/#search=Appearance

Caniuse is reporting that -webkit-appearance is only supported on IE11 Mobile. Nothing about Edge desktop...

**Comment by michaelwarren1106** [comment]
Just as an fyi, since it's a trusted resource

**Comment by dstorey** [comment]
@michaelwarren1106 Edge is listed there as partial. 

Having said that there is a spec now, and only none and auto are valid values, so I'll probably make a PR to set to full, once I double check auto works.

**Comment by michaelwarren1106** [comment]
Ok cool. I am seeing an issue using it in an app I'm building. I'll check
what build and send over a screenshot. Would there possibly be any issues
depending on what Windows theme is being used? We're corporate, and have
the classic theme on our machines instead of the newer ones. Would that
maybe make a difference?

**Comment by FremyCompany** [comment]
I think we support the interoperable subset now, but there is still no spec to link to.
