### ISSUE TITLE
Expose Opera Data

### ISSUE THREAD

**Issue by jacobrossi** [MicrosoftEdge/Status#29]
Working with Mathias on this

**Comment by jacobrossi** [comment]
We list 3 statuses for non-IE browsers:

Shipped
In Development
Not Supported

Shipped is easily determined thanks to the shipped_opera_milestone field in the Chromium Dashboard data. However, I'm not sure how we should be differentiating between In Development and Not Supported for Opera.  We use impl_status_chrome field for Chrome. But there doesn't seem to be a similar field for Opera. 

Given there are occasions that the shipping statuses of Chrome and Opera differ, it doesn't seem correct to just copy impl_status_chrome for Opera in this regard. We could at least use shipped_opera_milestone + meta.needsflag to list off-by-default features as "in development". However, there would still be a number of features in development for Blink that are listed as such for Chrome but not Opera.

@mathiasbynens - suggestions on what to do here?

**Comment by mathiasbynens** [comment]
> However, I'm not sure how we should be differentiating between In Development and Not Supported for Opera.

Everything that’s supported in Chromium is also something we want to / should implement in Opera — if not right now, then definitely at some point in the future. So if no `shipped_opera_milestone` is present, but the feature _is_ shipped in Chrome/Chromium, it can be considered as In Development for Opera.

Does that help?

**Comment by molant** [comment]
Thanks @mathiasbynens,
what about the features in development in Chrome? Should they also be in development for Opera?

**Comment by mathiasbynens** [comment]
@molant Yes.

**Comment by jacobrossi** [comment]
Ok, I updated this to work as described above. Note that I need to make one more commit to add Opera status for the features that are not in the Chromium Dashboard.  For these, @mathiasbynens , would it be correct to just copy the Chrome status?
- HTTP/2 (In Development)
- WebGL Instancing Extension (Shipped)
- CSS Transforms - preserve 3d (shipped)
- Cross-Domain Font Loading (Shipped)
- Object RTC API (Not Supported)
- setImmediate()  (Not Supported)
- Resource Priorities (Not Supported)
- Beacon (Not Supported)
- Prefetch attribute (Not Supported)
- Prerender attribute (Shipped)
- CSS Scrolling Snap Points (Not Supported)
- DOM L3 XPath (Shipped)
- Screen Orientation API (Not Supported)
- CSS pointer-events (Shipped)
- ES6 Array, Math, Number, & String Methods (In Development)
- Web Driver (Shipped)
- SVG Foreign Object (Shipped)
- Media Queries Level 4 pointer/hover (Shipped)
- Selection API (shipped)
- ES6 Object Literal Enhancements (Not Supported)
- SVG External Content in <use> (Shipped)

**Comment by mathiasbynens** [comment]
> For these, @mathiasbynens , would it be correct to just copy the Chrome status?

Yes.

Thanks for your work on this, @jacobrossi!

**Comment by jacobrossi** [comment]
Great- I've made the final change and will merge this in shortly. For reference, here's the list of features "In Development" in Opera but "Shipped" in Chrome (if there's a mistake, it's most likely in the shipped_opera_milestone field from the Chromium Dashboard):
- Media Source Extensions
- Quota Management API
- Web Notifications
- Web Speech API
- Shapes
