### ISSUE TITLE
Use sprites for images

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/Status#3]
We have 35+ small images. We should be using a sprite to redunce the number of server calls.
We could use something like https://github.com/Ensighten/grunt-spritesmith and replace the images to css-backgrounds

**Comment by molant** [comment]
investigating this while @dstorey changes the HTML

**Comment by dstorey** [comment]
Made changes to HTML and CSS at https://github.com/InternetExplorer/Status.IE/tree/imgToBgImg

**Comment by molant** [comment]
All yours. You have the code in the branch css-sprite-generation a796ed0d15e646e308145d4bd2b8293bd2d392cd

**Comment by molant** [comment]
This should be fixed in 6da98597ff90c0f3ad2b985e6448a12c409fa3d2
