### ISSUE TITLE
Improve Filtering

### ISSUE THREAD

**Issue by jacobrossi** [MicrosoftEdge/Status#30]
User feedback to address:
- Not clear that browser drop down means "features with shipped status in this browser"
- Multiple filters seems too heavy weight, one text filter is probably sufficient and saves UI space
- Use clearer terms (e.g. "Implementation Status" rather than just "Status")
- Can't filter on mobile

I will mock up some possible alternatives.

**Comment by molant** [comment]
Should we close #1 in favor of this one?
+@dstorey

**Comment by dstorey** [comment]
This is now complete.
