### ISSUE TITLE
Add Element.closest()

### ISSUE THREAD

**Issue by cvrebert** [MicrosoftEdge/Status#304]
i.e. https://developer.mozilla.org/en-US/docs/Web/API/Element/closest
It's been implemented in all the other major browsers.

UserVoice link: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10119510-element-closest

**Comment by laurent-le-graverend** [comment]
:+1:

**Comment by FremyCompany** [comment]
Now supported, 
I think it's fair to close without updating, we cannot add every function in the status.
