### ISSUE TITLE
SVG feBlend With in2 from a resized feImage result linking to an embedded SVG document rendered wrong

### ISSUE THREAD

**Issue by tanty** [MicrosoftEdge/Status#309]
[Reproduced with IE11 on Win 8.1](https://dev.modern.ie/tools/screenshots/#https://rawgit.com/tanty/design-hodgepodge/master/svg/filter/feBlend-feImage-resized-tests.html)
![win8 1_ie_11 0](https://cloud.githubusercontent.com/assets/1577005/10554269/a427ff8c-746a-11e5-9edf-3e25828e07c9.png)
# Steps to reproduce the problem:

Open the URL:
https://rawgit.com/tanty/design-hodgepodge/master/svg/filter/feBlend-feImage-resized-tests.html
# What is the expected behavior?

All the SVGs are shown as the included PNG as reference
# What went wrong?

The feImage in the SVG documents explicits values for x=0, y=0, width=172.8%, height=172.8%, which is the same value than the embedded document's height.

None of the SVGs, regardless of whether the embedded SVG document specifies a "viewBox" with values "0 0 <SVGWidth> <SVGHeight>" which, AFAIK, are the default values for the viewBox, are rendered correctly.
# Related issues
- #307
- #308 
# Similar issues in other web engines
- [WebKit](https://bugs.webkit.org/show_bug.cgi?id=150258)
- [Chromium](https://code.google.com/p/chromium/issues/detail?id=544180)

**Comment by jacobrossi** [comment]
This repo isn't the right place to file bug reports. If you haven't already, please file at http://connect.microsoft.com/ie

**Comment by tanty** [comment]
Reported at: https://connect.microsoft.com/IE/feedback/details/1910044
