### ISSUE TITLE
Pin Tabs

### ISSUE THREAD

**Issue by TheJaredWilcurt** [MicrosoftEdge/Status#314]
I know this isn't an HTML5/CSS3 spec, just a general browser feature, but It's needed.

Today, for the first time since IE6, I genuinely considered switching to IE as my default browser. Unfortunately when attempting to match my normal set up I found IE 11 doesn't support pinned tabs in the way Chrome, Chromium, Canary, Opera, Firefox, Vivaldi, and Safari do.

It would also be nice to have more control over the UI and where elements are positioned. IE6 was highly customizable, where as in comparison 11 feels like a step backwards, like I've lost capabilities.

Also, if your intention is to retake market share and to get back up to majority status (and why wouldn't that be your goal), why are you preventing users of your own OS from using the latest versions? Your competition goes out of the way to support older versions of Windows. If I'm on Vista or 7, and Microsoft still supports them, why can't I use a Microsoft made browser (Edge)? You're intentionally cutting off portions of your audience from having access and diminishing your market reach. Specifically the part of the market most likely to like IE, Microsoft users themselves. Kind of ridiculous. It'll be 5-10 years before I leave Windows 7, which means I'm going to be using your competition, as IE 11 is the best you can do and it can't even pin tabs.

Please do better guys.

**Comment by patrickkettner** [comment]
Hey @TheJaredWilcurt!
As you mentioned, this isn't really the place for a request like this since this tracks features. Since this is a application feature, and not a web platform feature, this would go in our [web apps user voice](https://windows.uservoice.com/forums/285214-microsoft-edge?query=pinned%20tabs) where you will see there is a request for this [here](https://windows.uservoice.com/forums/285214-microsoft-edge/suggestions/7436488-add-the-ability-of-pinning-tabs).

**Comment by TheJaredWilcurt** [comment]
You link me to a page that says "The concept of Microsoft listening to it's users was fun for a while, but we're gonna stop now". None of the posts on there can be voted on, even the most recent one from last week.

You've effectively pointed to a wall for me to go yell at. No thanks.

**Comment by lenovouser** [comment]
Yeah, I kind of share @TheJaredWilcurt's opinion. I really like Edge, but things like not being able to use a AdBlocker, or actually any plugin is stopping me from using it at the moment. Also slow adaption or even no adaption of features like Subresource Integrity, Service Workers. WebP / WebM, WebGL 2.0 and WOFF2 from "competitors" like Google are annoying to me as a web developer.

**Comment by dstorey** [comment]
@TheJaredWilcurt @lenovouser feedback for the MS Edge app should be posted in the Windows Feedback app (there is a link to it from the ellipsis (…) menu in the browser. This is where the app teams are consolidating their feedback experience.

Web Platform and developer facing (such as F12) features should still be filed on uservoice: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer
