### ISSUE TITLE
No UserVoice links on the Platform Status page?

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#315]
The UserVoice links and vote counts on the [status page](https://dev.windows.com/en-us/microsoft-edge/platform/status/adownloadattribute) disappear. Is this intentional?

**Comment by molant** [comment]
Definitely not intentional. Something has probably broken during the migration to the new domain. Will look into it as soon as I can

**Comment by molant** [comment]
This is fixed now. Thanks!
