### ISSUE TITLE
Need to update Status entries for Fall Update

### ISSUE THREAD

**Issue by kypflug** [MicrosoftEdge/Status#316]
Builds <= 10240 should be Microsoft EdgeHTML 12.[Build]
Builds 10241-10586 should be Microsoft EdgeHTML 13.[Build]

**Comment by Studio384** [comment]
I second this, data isn't that useful if it is running behind. Why do you guys update so quickly after an Insider Preview (which is good), but let it drag on so long after an official release? When Windows 10 went to public it took 10 days before the status page got updated!

**Comment by kypflug** [comment]
Fixed in #313
