### ISSUE TITLE
Sharepoint 2013 Content Organizer

### ISSUE THREAD

**Issue by francescaBersanetti** [MicrosoftEdge/Status#318]
Hi, 
i should try to configurate the content organizer features for Sharepoint 2013. I would like to use it to create a workflow that transfer a document by site to another site of Sharepoint.
Do you know how can i do? Please give me a list of instructions step by step of all i should do ( from the basic level).

Thank you very much

**Comment by jacobrossi** [comment]
This is not a support forum for SharePoint.  Try the [SharePoint 2013 MSDN Forum](https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=sharepointgeneral)
