### ISSUE TITLE
Website issue: Links don't work

### ISSUE THREAD

**Issue by mkurz** [MicrosoftEdge/Status#321]
On https://dev.windows.com/en-us/microsoft-edge/platform/status/ the four links on to left bottom to GitHub, StackOverflow, Platform Status and demos don't work.

**Comment by molant** [comment]
Tracking this internally, fix should go live soon.

Thanks!

**Comment by mkurz** [comment]
The links are still not working....

**Comment by molant** [comment]
Check again :)
Thanks!

**Comment by mkurz** [comment]
Works :+1:
