### ISSUE TITLE
a[download] attribute broken

### ISSUE THREAD

**Issue by mobilekosmos** [MicrosoftEdge/Status#334]
Here you say that this was implemented https://dev.windows.com/en-us/microsoft-edge/platform/status/adownloadattribute

but e.g. following does not work:
<a class="saveFileButton" id="saveFileButton" href="blob:null/342146e3-8efa-4f5b-b248-69cae90fb826" download="%html_filename%"></a>

Also following check results in false: 
var downloadAttributeSupported = 'download' in document.createElement('a');

**Comment by phistuck** [comment]
You probably meant https://dev.windows.com/en-us/microsoft-edge/platform/status/adownloadattribute and this issue tracker is not a Microsoft Edge issue tracker, but a platform status issue tracker.
Microsoft Edge issues should be filed using http://connect.microsoft.com/ie.
Also, note that if some aspect of the feature does not work (have you tried actually using it in HTML rather than in JavaScript?), this does not render the entire feature as not supported.

**Comment by ghost** [comment]
The check returns true for me on Windows 10 Build 10586.
`navigator.userAgent`
`"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"`
`'download' in document.createElement('a');`
`true`

**Comment by mobilekosmos** [comment]
Yes, that's the problem, you get true but then you add a blobUrl to the href atribbute and nothing happens when pressing the download button. With following code we handle the issue for now:

``var blob = new Blob([source], { type: "application/octet-stream" });

var saveFileButton = document.getElementById("saveFileButton");

var downloadAttributeSupported = 'download' in document.createElement('a');

if (downloadAttributeSupported && !isMicrosoftEdge()) {
  var blobURL = window.URL.createObjectURL(blob);
  saveFileButton.download = "filename.txt";
  saveFileButton.href = blobURL;
} else {
  saveFileButton.onclick = function () {
  window.navigator.msSaveOrOpenBlob(blob, '"filename.txt"');
}``

**Comment by phistuck** [comment]
Move this to connect, please. This is not the place.

**Comment by molant** [comment]
Hi @tererecool, thanks for catching this. Please open an issue in [connect](https://connect.microsoft.com/ie) as @phistuck has suggested before.
