### ISSUE TITLE
Update some of the browser logos

### ISSUE THREAD

**Issue by alrra** [MicrosoftEdge/Status#335]
- [x] Update the [Internet Explorer logo](https://github.com/alrra/browser-logos/blob/49e362d39248e6d7a1419fed249749c97cb6be3a/internet-explorer/internet-explorer.png) to better reflect the official one
  
  ![](https://cloud.githubusercontent.com/assets/1223565/12380837/e0a184c0-bd84-11e5-9a0f-dd2ca09b5cf9.png)
- [x] Update the [Opera logo](https://github.com/alrra/browser-logos/blob/master/opera) (the current one is the logo used by [Opera v15-32](https://github.com/alrra/browser-logos/blob/3bcbb22ff8bbfd753f8fe8bd1e0ea5b3dadb84a3/archive/opera_15-32/opera_15-32.png))
  
  ![](https://cloud.githubusercontent.com/assets/1223565/12380847/10c9cd10-bd85-11e5-941a-6c4fbaecb228.png)
- [x] Update the [Chrome logo](https://github.com/alrra/browser-logos/tree/master/chrome) (the current one is the logo used by [Chrome v11-48](https://github.com/alrra/browser-logos/blob/03ded7c383385bc564a8929e162968d0fa953674/archive/chrome_11-48/chrome_11-48.png))
  
  ![](https://cloud.githubusercontent.com/assets/1223565/13637238/ef6f5880-e60e-11e5-9f0c-593f91e88871.png)

**Comment by alrra** [comment]
Starting with version `49`, Chrome also changed its logo (updated my [previous comment](https://github.com/MicrosoftEdge/Status/issues/335#issue-127133458)).

**Comment by Studio384** [comment]
Both the Internet Explorer logo and Opera logo have already been updated.
