### ISSUE TITLE
Input type color 

### ISSUE THREAD

**Issue by rjpond** [MicrosoftEdge/Status#337]
Elements of type input=color are not supported by Edge currently.  Almost all other HTML5 input types are supported.  I feel this would be useful.  It is not listed on the Edge platform roadmap as planned - but nor is it listed as 'not currently planned', so it's unclear whether it's been considered at all.

**Comment by cvrebert** [comment]
Apparently it's in development (per https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6514216--input-type-color ), although missing from the Status site.

**Comment by rjpond** [comment]
The status update at uservoice was added more than a week after I posted the above, so I don't know if it was in reaction to me raising the issue here, or coincidence.  Thanks though, and thanks to the person who updated uservoice.

**Comment by kypflug** [comment]
Thanks for catching the discrepancy @cvrebert! Just added this.
