### ISSUE TITLE
Link to WHATWG instead of the W3C spec?

### ISSUE THREAD

**Issue by alrra** [MicrosoftEdge/Status#339]
See: https://annevankesteren.nl/2016/01/film-at-11.

**Comment by jacobrossi** [comment]
Thanks @alrra.  Microsoft [prefers the W3C](https://github.com/MicrosoftEdge/Status/blob/production/CONTRIBUTING.md#updating-features) as the place for developing interoperable open web standards. We believe this organization provides additional valuable structure that does not currently exist in the WHATWG. In particular, the W3C serves as a governance entity that ensures web standards are advanced with consensus from the stakeholders (browser vendors, other standards contributors, etc.), a structured way to arbitrate disagreements, and an enforced and documented IP policy that ensures the web platform stays open and free.  

Therefore, we'll keep status pointing to W3C specs except in instances where there is no W3C spec or other special cases.

At the same time, we recognize the inefficiencies of having two competing bodies developing similar specs.  We're actively working with the other browser vendors, W3C, and WHATWG editors on ways to better align.
