### ISSUE TITLE
Add platform integration?

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#34]
It would be nice to include some platform integration where it makes sense.

I’m mainly thinking of Live Tile support for Windows, preferably with a feed of the the latest features that are added of have their status change. If we do this we may as well add an RSS feed of the same data.

**Comment by dstorey** [comment]
If http://status.modern.ie/webnotifications moves beyond “under consideration” it could also be interesting to add as a way to notify opt-in users of updated features tracked by the site.

**Comment by molant** [comment]
What information should the RSS feed or the live tiles give? I'm thinking about the status change of features. Should it be individual items or be all compiled into one single (big) item? Maybe one item per push so if 5 features are updated/added at the same time that will make one item in the feed?

**Comment by dstorey** [comment]
Closing this as the actual website is part of the wider dev.modern.ie now.
