### ISSUE TITLE
microsoftedge.com doesn't support HTTPS

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#346]
https://www.microsoftedge.com/, https://status.microsoftedge.com/, and https://uservoice.microsoftedge.com/ cannot be connected. On README.md, there is a link to [UserVoice](https://uservoice.microsoftedge.com/), which is currently broken until HTTPS support is added.

**Comment by dstorey** [comment]
CC @molant

**Comment by molant** [comment]
@kypflug is working on that

**Comment by kypflug** [comment]
We're on the list for the next quarterly refresh of the master cert and expect the redirect to be working with HTTPS in April.

**Comment by kypflug** [comment]
HTTPS should be working as expected sometime next month.

**Comment by kypflug** [comment]
Should be fixed now!
