### ISSUE TITLE
onaddtrack Event doesn't seem to fire in Edge, MSDN docs support that it's implemented up to IE11

### ISSUE THREAD

**Issue by ram651** [MicrosoftEdge/Status#354]
I've been trying to determine whether or not the onaddtrack event is being fired in Edge for Audio/Video elements.

I'm fairly sure that it isn't currently supported, as the main docs only show it up till IE11 and the current Edge Status page doesn't mention specifics about each of the features currently supported.

From those in the know, is the ontrackadd event currently supported by Edge?

If so, what are the Edge distinctions for the event, as opposed to the other major browsers?

If not, any idea of the projected inclusion of it on the roadmap, if at all?

Example of how I'm binding the onaddtrack event to the player(Currently supported across the board):

``` javascript
videoElement.textTracks().addEventListener('addtrack', function(addTrackEvent){
     // code based on track added
}, false);
```

**Comment by molant** [comment]
Hello @ram651,

this is not the right place to ask questions. If you have found any bugs in the platform please report them in https://connect.microsoft.com/ie

The [Microsoft Edge API reference](https://dev.windows.com/en-us/microsoft-edge/platform/documentation/apireference/) lists all the interfaces and APIs implemented in the browser and [addtrack](https://dev.windows.com/en-us/microsoft-edge/platform/documentation/apireference/events/addtrack/) is in there.
