### ISSUE TITLE
Remove `app/static/ie-status.json`?

### ISSUE THREAD

**Issue by alrra** [MicrosoftEdge/Status#357]
Currently there are two files that contain basically the same data:
- [`status.json`](https://github.com/MicrosoftEdge/Status/blob/bb80445f240ffad8c047fd55d2c198fc3fe4aebd/status.json)
- [`app/static/ie-status.json`](https://github.com/MicrosoftEdge/Status/blob/bb80445f240ffad8c047fd55d2c198fc3fe4aebd/app/static/ie-status.json)

From [this commit](https://github.com/MicrosoftEdge/Status/commit/419e735b21263b45f951b8a7e856a924ce7f200f) is seems to me that `app/static/ie-status.json` doesn't need to exist anymore.
## 

Note: Some data from `app/static/ie-status.json` may need to be imported into `status.json` (here is the [diff between `status.json` and `app/static/ie-status.json`](https://gist.github.com/alrra/0612e8798cc077c46177)).

Cc: @molant, @jacobrossi.

**Comment by alrra** [comment]
Here is the [diff between `status.json` and `app/static/ie-status.json`](https://gist.github.com/alrra/0612e8798cc077c46177).

**Comment by jacobrossi** [comment]
Yeah, this is intentional staging.  We'll be removing app/static/ie-status.json once the web server is pull from the new file location in this repo (status.json).

**Comment by jacobrossi** [comment]
eh, I'll leave this open until we actually remove it anyway ;-)

**Comment by alrra** [comment]
Fixed by https://github.com/MicrosoftEdge/Status/commit/f34e1adf3d5ef30bf2f973299abc0a0f17676c17.
