### ISSUE TITLE
ServiceWorkers!!

### ISSUE THREAD

**Issue by paramsinghvc** [MicrosoftEdge/Status#359]
Please get the serviceworkers feature quickly, other browsers have got it already! Waiting !

**Comment by alrra** [comment]
@paramsinghvc 

From https://dev.windows.com/en-us/microsoft-edge/platform/status/serviceworker:

> Roadmap Priority: **High — We intend to begin development soon**.

## 

Note: This issue tracker is not intended for making feature requests (please see: https://github.com/MicrosoftEdge/Status#contributing).
