### ISSUE TITLE
Show status of APNG on Status tracker

### ISSUE THREAD

**Issue by ericlaw1979** [MicrosoftEdge/Status#361]
http://caniuse.com/#search=apng
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6513393-apng-animated-png-images-support-firefox-and-sa

**Comment by ericlaw1979** [comment]
Arguably dupe of https://github.com/MicrosoftEdge/Status/issues/98 which hasn't been touched in a long time and doesn't use the acronym APNG

**Comment by maxstepin** [comment]
A couple of recent quotes from Chrome devs: "Yup, we've decided to move forward with this", "tentatively have that set up to start in Q4"

Worth tracking.

**Comment by alrra** [comment]
Closing in favor of #477.
