### ISSUE TITLE
Provide callback or change event on autofill

### ISSUE THREAD

**Issue by maxinacube** [MicrosoftEdge/Status#362]
With IE ignoring `autofill=off`, my site is having some major issues on user registration forms and user profile forms. We use a password strength meter to ensure all users have strong passwords, and I understand `autofill=off` is ignored for passwords to encourage stronger passwords with ease of use.

The issue arises when the password is autofilled, because there is no change event detected and no sort of callback to say that the password was filled. In my scenario, this causes the password strength meter to never run and that snowballs into the form's registration button staying disabled because "No strong password is present".

I've found workarounds for Chrome, Firefox and Safari but there is nothing out there for IE as it's the only browser that doesn't do it on initial load or trigger a change event when the field is autofilled.

The autofill can be handled so much better in ways that don't hurt a website's performance, please look into this! The choice to ignore autofill AND give no context to when a field has been filled must be considered a bug.

**Comment by molant** [comment]
Hello @maxinacube,
This repo is only for things related to the status data available in https://status.microsoftedge.com. To report issues please go to https://connect.microsoft.com/ie
