### ISSUE TITLE
Missing implementation of ParentNode.children api?

### ISSUE THREAD

**Issue by vedmack** [MicrosoftEdge/Status#368]
Hi

It looks like there is no implementation of the [ParentNode.children](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children) api in Edge, consider the following code

```
var myXml = "<wrapper><inner><first>111</first><second>222</second></inner></wrapper>";
var parser=new DOMParser();
var xmlDoc=parser.parseFromString(myXml,"text/xml");
```

While in other browsers (including older IE) , the following `xmlDoc.firstChild.children` would return a list of HTML elements (HTML Collection object), in Edge it does not (return undefined)

See the following [jsfiddle test case](https://jsfiddle.net/5ke81x0q/)

**Comment by NoNameProvided** [comment]
Hi vedmack! 

This repo goal is to maintain the development status for features in Edge, to send developer feedback for features in Edge you can use the [javascript section of the uservoice site](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/category/86948-javascript).

**Comment by vedmack** [comment]
Ok,

Posted over there... https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/12957081-add-implementation-of-parentnode-children-api

Thanks
