### ISSUE TITLE
the previous window height and width has been taken in window.open method for edge browser

### ISSUE THREAD

**Issue by SangiliSabapathy** [MicrosoftEdge/Status#372]
1. i have test.html page from which i have tried to open tes1.html with size of 220 and 200
2. after that when i try to open blank page from tes1.html with size of 600 and 300.
3. the blank page is not OPENING WITH THE EXPECTED SIZE 600 AND 300 WHEREAS IT IS OPENING WITH THE PREVIOUS PAGE ZIE THAT IS 200 AND 200. 

NOTE: THIS ISSUE IS NOT HAPPNEING IN EDGE BROWSER VERSION 20.10240.16384. it is happening on 25.10586 version. 

convert the attached files from txt to html and try. 

please do the needful ASAP.

[tes1.txt](https://github.com/MicrosoftEdge/Status/files/193260/tes1.txt)
[test.txt](https://github.com/MicrosoftEdge/Status/files/193261/test.txt)

**Comment by alrra** [comment]
@SangiliSabapathy 

> Note that this GitHub project is **not** for making feature requests for or reporting bugs in Internet Explorer or Microsoft Edge. Browser feedback can be provided at [Microsoft Connect](https://connect.microsoft.com/ie) and [UserVoice](https://uservoice.microsoftedge.com).

(from: https://github.com/MicrosoftEdge/Status#contributing)

**Comment by hax** [comment]
There are too many bug reports in this repo.

I think Edge team should consider creating a github repo for bug reporting, because Connect/UserVoice is not very friendly for the developers.

**Comment by jacobrossi** [comment]
Great idea! ☺

**Comment by molant** [comment]
Agree! Let's see what we can do about that.

**Comment by alrra** [comment]
> There are too many bug reports in this repo.

Adding a [`ISSUE_TEMPLATE.md`](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) file containing a [short note](https://github.com/MicrosoftEdge/Status#contributing) could help in that regard.

## 

See also: https://github.com/blog/2111-issue-and-pull-request-templates
