### ISSUE TITLE
Add Intersection Observer to platform status

### ISSUE THREAD

**Issue by zhaoz** [MicrosoftEdge/Status#376]
Intersection Observer is not on the platform status page.

https://www.chromestatus.com/features/5695342691483648
https://rawgit.com/slightlyoff/IntersectionObserver/master/index.html
https://github.com/WICG/IntersectionObserver/blob/master/explainer.md

**Comment by jacobrossi** [comment]
Yes, we should have this added. Let me check with the layout team on the right priority level and we'll get it added. Thanks @zhaoz !

**Comment by jacobrossi** [comment]
@gregwhitworth or @chumpchief  could you maybe do a PR for this one?

**Comment by gregwhitworth** [comment]
I'll take this one @chumpchief
