### ISSUE TITLE
A lot of links to api catalog are broken

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/Status#378]
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/mediacaptureandstreams
the link for `See detailed support` points to https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/spec/mediacapture which is broken (there are several mediacapture apis but none with that shortname).

There are more than just the media capture. We should review all the links and make sure they point to the right place.

ping @jacobrossi @arronei

**Comment by molant** [comment]
@josephshum, @arronei who did the integration? Can one of you take a look at this?

**Comment by ghost** [comment]
@molant I am on it.
