### ISSUE TITLE
Backdrop Filters

### ISSUE THREAD

**Issue by drcreek** [MicrosoftEdge/Status#380]
This is now fully shipped in Safari, Mobile Safari and Can be enabled with flags in Chrome. Firefox has it in development. I believe it also is working the in the Opera Beta but for some reason I can't install to verify.

**Comment by cvrebert** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/backdropfilter

**Comment by drcreek** [comment]
I know about that. 

I'm suggesting that it should be more than just "under consideration" and given higher priority.

**Comment by jacobrossi** [comment]
Thanks for the feedback. However, this isn't the right forum to provide it. :-) Please see the entry in our User Voice for this where you can upvote and chime in with comments:
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/9160189-backdrop-filters
