### ISSUE TITLE
Add Promises

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#39]
Promises are one of those features that have received a lot of buzz, and are included in many JavaScript frameworks. It would be good to include on Status.
- [Can I Use entry](http://caniuse.com/#feat=promises)
- [ES6 Spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise-objects)

**Comment by charlesjmorris** [comment]
It's there now! http://status.modern.ie/promiseses6
