### ISSUE TITLE
Create task to verify links

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/Status#40]
Maybe we should create a task in the build process that will check the validity of the links in our JSON data.
Pros:
- We are sure our links are working
  Cons:
- Validation can take a while to check all the links even if paralleled (maybe it could be a separate task that is not build?)

@jacobrossi, @dstorey thoughts?

**Comment by dstorey** [comment]
Closing this as the actual website is part of the wider dev.modern.ie now.
