### ISSUE TITLE
Expand/Collapse Arrow Animation Sluggish in Edge

### ISSUE THREAD

**Issue by kirupa** [MicrosoftEdge/Status#416]
Hi everybody!
When you click on a feature row, the feature expands to show additional details. As part of expanding to show additional details, the expand/collapse arrow on the right rotates. This rotation is pretty sluggish on Edge, but it is really snappy in Chrome.

I can attach an animated GIF/video of this issue if it helps.

Thanks,
Kirupa

**Comment by molant** [comment]
@gregwhitworth I remember talking about this with you and maybe it was a regression? I don't think it repros on IE11

**Comment by gregwhitworth** [comment]
@molant can you provide a reduction and file a bug on Comp as I suspect you're doing this with keyframes on a rotation and that will be their issue to look into. Thanks.

**Comment by molant** [comment]
I can probably try to do that later this week if @kirupa doesn't have time before :)
Thanks!

**Comment by jacobrossi** [comment]
Do we have a trace to show where the time is spent? I'm betting this is layout perf not comp because it changes the height.

**Comment by gregwhitworth** [comment]
No, we'll put it on the right team once we get a reduction.

**Comment by FremyCompany** [comment]
This was a long time ago; closing
