### ISSUE TITLE
Push API and Service Worker - Firefox - Support

### ISSUE THREAD

**Issue by PascalReintjens** [MicrosoftEdge/Status#419]
Hello,

I think there is an update for: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/pushapi. The site lists the Push API still "In Development" by Firefox, although the linked https://bugzilla.mozilla.org/show_bug.cgi?id=1038811 is resolved fixed. Mozillas own platform lists the Push API as supported since Firefox 44: https://platform-status.mozilla.org/#push - See as well: http://caniuse.com/#search=push and Browser compatibility table: https://developer.mozilla.org/de/docs/Web/API/Push_API

And for Service Workers: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/serviceworker: Although it's not completely finished, there seems to be partial (nearly full) support since Firefox 44, they even consider it "landed" themselves: https://platform-status.mozilla.org/#service-worker. I am therefore not sure, whether "In development" is the right status (for more comparison see also https://jakearchibald.github.io/isserviceworkerready/)

**Comment by molant** [comment]
Hello @PascalReintjens,

Almost all the information for other browsers comes from the [Chromium dashboard](https://github.com/MicrosoftEdge/Status/blob/production/CONTRIBUTING.md#updating-features). If there is an error you should open an issue [there](https://github.com/GoogleChrome/chromium-dashboard) :)

For the two cases you mention, you can check that we don't have any value in our json other than for IE and Edge:
- [Push API](https://github.com/MicrosoftEdge/Status/blob/production/status.json#L2706)
- [Service Worker](https://github.com/MicrosoftEdge/Status/blob/production/status.json#L2033)

Thanks!

**Comment by PascalReintjens** [comment]
Hello @molant, 

Thanks for the quick response. 

I opened an issue on the Chromium dashboard too, so I hope this should be updated soon :)
