### ISSUE TITLE
Accordions and drop downs need to be accessible via keyboard

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#42]
The accordions and drop downs (in the filters branch) can be accessed via the tab key, but there is no way to expand them (I suppose via the enter key?) This needs to be added.

**Comment by dstorey** [comment]
Feedback from Léonie:

The accordion functionality is working ok, except for the keyboard handling. When a keyboard user tabs onto the first accordion header, it should be possible to use the cursor keys to cycle between the other accordion headers. This doesn’t seem to be happening at the moment.

The ARIA authoring practices has a useful design pattern that includes recommended keyboard handling:
http://www.w3.org/TR/wai-aria-practices/#accordion

**Comment by molant** [comment]
So the down/up arrow should do the same as tab/shift-tab, right?

**Comment by dstorey** [comment]
Sounds like it, yes.
