### ISSUE TITLE
CSS Variables shipped in Safari according to chromestatus

### ISSUE THREAD

**Issue by scheinercc** [MicrosoftEdge/Status#420]
Status for Safari on 
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/cssvariables
differs from
https://www.chromestatus.com/feature/6401356696911872

... which points to here: https://webkit.org/status/#specification-css-variables
(not quite sure if that means it is shipped in Safari, though?!)

**Comment by jacobrossi** [comment]
Huh. Odd.  This feature is set up to pull Safari's status from ChromeStatus.  So I'm not sure why it's coming through wrong. Will need to debug.

**Comment by jdalton** [comment]
Looks like a browser caching issue. Try clearing your cache.

<img width="966" src="https://cloud.githubusercontent.com/assets/4303/17738581/b203330c-6446-11e6-901c-8f63ca6b9234.png">

Might be cool to see about busting the cache on the site side for folks.

**Comment by molant** [comment]
Right now all the JSON data is put directly into the HTML (we will be changing this in the next couple weeks) so I don't think that is the problem.
We pull the chromestatus data every few minutes. Its `features.json` file has a max-age of 600 so depending on when it is updated, and when we pulled it for the last time it could take a bit to get it.
