### ISSUE TITLE
Support for referrerpolicy attribute

### ISSUE THREAD

**Issue by pricop** [MicrosoftEdge/Status#424]
Are there any plans regarding the implementation of the referrerpolicy attribute to allow the control of referral value per item rather than per entire page, (using the meta referrer - which by the way still uses the legacy keywords rather than the new ones, see the **Note** mentioned here: https://w3c.github.io/webappsec-referrer-policy/#determine-policy-for-token)?

For example, I could load an image from a 3rd party website on a page, without the user's referrer to be sent out when the image request is made (https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery).

The referrer policy draft is available at: https://www.w3.org/TR/referrer-policy/

Chrome already supports this.

**Comment by martinsuchan** [comment]
Even though the [Platform Status shows Meta Referrer as supported](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/metareferrer/?q=referrer), only the **older draft is supported** with values: ```never, always, origin & default```
Edge should really support the current [Editor's Draft on Referrer Policy](https://w3c.github.io/webappsec-referrer-policy/), just like Firefox/Chrome/Opera.
See this issue for details: 
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7119603/

**Comment by pricop** [comment]
Since Edge has moved to the Chromium engine, this issue does not exist anymore.
