### ISSUE TITLE
Update Fullscreen API status

### ISSUE THREAD

**Issue by saschanaz** [MicrosoftEdge/Status#437]
It seems Edge 14 dropped unprefixed Fullscreen API while keeping the `-webkit-` one. I don't know why but the platform status page should say something about this.

**Comment by jacobrossi** [comment]
Yes, indeed. We dropped it due to some compatibility issues.  We'll be bringing this back on or around the time other browsers do it in coordination.  We should get this updated in the meantime though. Thanks for filing the issue!

**Comment by kypflug** [comment]
Fixed in #438
