### ISSUE TITLE
Brotli support update.

### ISSUE THREAD

**Issue by jdalton** [MicrosoftEdge/Status#440]
Brotli is now supported in Chrome, Firefox, and Opera ([caniuse](http://caniuse.com/#feat=brotli)) we should update the status

<img width="980" src="https://cloud.githubusercontent.com/assets/4303/17715919/5b25f622-63bb-11e6-8262-4af76415c02f.png">

I looked at the `status.json`, but I'm not sure what to toggle.

**Comment by jdalton** [comment]
I looked at the `status.json` but not sure what to toggle.

**Comment by molant** [comment]
More info in https://github.com/MicrosoftEdge/Status#contributing :)

**Comment by jdalton** [comment]
It seems to be up-to-date [on Chrome's status](https://www.chromestatus.com/features/5420797577396224). Is this a syncing issue?

**Comment by molant** [comment]
Depending on when it got updated. If it is recently maybe, if it is was a while ago then there might be something else going on. Are we using the right id (5420797577396224)?

**Comment by jdalton** [comment]
The id looks correct.

**Comment by alrra** [comment]
> Is this a syncing issue?

Maybe a caching issue? For me, the [status](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/brotlicompresseddataformat) is up to date.

![](https://cloud.githubusercontent.com/assets/1223565/17727677/a20c1d66-6463-11e6-8c29-42f117009c9d.png)

**Comment by jdalton** [comment]
Imma say it was fixed in the 10 hours between comments 😝

**Comment by ghost** [comment]
Could you also fix #420? That is a similar issue about wrong status of CSS Variables.

**Comment by molant** [comment]
Haven't changed anything for brotli so probably cache and syncing. Closing.
