### ISSUE TITLE
Add An Entry For EventListenerOptions

### ISSUE THREAD

**Issue by phistuck** [MicrosoftEdge/Status#442]
`window.addEventListener(type, handler, {capture: boolean, passive: boolean, once: boolean});`
Firefox and WebKit (including Safari technology preview) recently implemented them. Chrome implements the first two and the third is in development.

Basic support and `capture` - https://www.chromestatus.com/feature/5718574840676352
`once` - https://www.chromestatus.com/feature/5630331130478592
`passive` - https://www.chromestatus.com/feature/5745543795965952
`AddEventListenerOptions` separation - https://www.chromestatus.com/feature/6540125429301248

**Comment by jacobrossi** [comment]
This might make sense to split up?  I think  just "once" and "passive" are really the important _new_ things to track here.

**Comment by phistuck** [comment]
Yeah, split it however you like, I would just like to see this added to the platform status, one way or another. :)

**Comment by phistuck** [comment]
Hopefully, with an "In development" status. :P

**Comment by jacobrossi** [comment]
The area owner for this is on vacation. I'll get this added as soon as he's back and I have a chance to get the latest from him.

**Comment by cvrebert** [comment]
So, did you get a chance to talk to the owner?

**Comment by saschanaz** [comment]
Once: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/eventlisteneronceoption/?q=once
Passive: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/passiveeventlisteners/?q=passive

Both are in development :smile:
