### ISSUE TITLE
Track: prepend, append, before, after, and replaceWith

### ISSUE THREAD

**Issue by ParkFramework** [MicrosoftEdge/Status#467]
```
  void prepend(Node | DOMString... nodes);
  void append(Node | DOMString... nodes);
  void before(Node | DOMString... nodes);
  void after(Node | DOMString... nodes);
  void replace(Node | DOMString... nodes);
```

https://dom.spec.whatwg.org/#childnode
https://bugs.webkit.org/show_bug.cgi?id=74648
https://bugzilla.mozilla.org/show_bug.cgi?id=911477
https://www.chromestatus.com/features/5723067795898368

**Comment by cvrebert** [comment]
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/16036408

**Comment by FremyCompany** [comment]
It is tracked by now (and in case you missed this, it is in the very latest preview build, or will be in the next one)

**Comment by cvrebert** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/domparentnodemethodsprependappendandchildnodemethodsbeforeafterandreplacewith/
