### ISSUE TITLE
Incorrect status for FIDO U2F support in Firefox

### ISSUE THREAD

**Issue by Chaz6** [MicrosoftEdge/Status#468]
FIDO U2F is supported in Firefox with an extension. It is currently shown as "Not supported" which is misleading.

**Comment by molant** [comment]
Support for other browser comes from the Chromium Dashboard as explained in the [contributing section](https://github.com/MicrosoftEdge/Status#contributing). If you think it should be marked as supported in Firefox I recommend you to open an issue in that project.

Thanks!
