### ISSUE TITLE
Encoding Standard browser support info is not quite correct

### ISSUE THREAD

**Issue by domenic** [MicrosoftEdge/Status#470]
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/encodingstandard/ says not supported in Chrome and Firefox, but it is. The "Detailed browser support" linking to https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?q=specName%3Awhatwg-encoding even confirms this.

**Comment by molant** [comment]
Hi @domenic,  do you have an id from ChromeStatus we can use to track this? At the moment it is [null](https://github.com/MicrosoftEdge/Status/blob/production/status.json#L5883) and that's the reason why the info is not correct.

**Comment by domenic** [comment]
It looks like it is https://www.chromestatus.com/feature/5714368087982080

**Comment by molant** [comment]
@domenic updated. It can take a few minutes until the changes are propagated.
