### ISSUE TITLE
Platform Status Update by Device Type

### ISSUE THREAD

**Issue by glennphilp** [MicrosoftEdge/Status#491]
Is it possible to get an update field/column on the Web Platform status based on device type?

For instance, it is not possible to use all APIs and features on a mobile device and it requires a lot of testing and digging to find this information. What would be nice is to have fields/columns that would tell developers if the feature is available for Edge on PC, Tablet, or Phone. And if it isn't, then whether it is under consideration, in development, or won't be coming to Edge on the device.

**Comment by glennphilp** [comment]
Actually it might be simpler to create a mobile, desktop, tablet device flag and then add the 3 options under the advanced filter on Edge Web Platform Status

**Comment by molant** [comment]
we are looking into adding this feature and looking into some ideas internally. Hopefully we should have something in the next sprint or so.

**Comment by alrra** [comment]
![](https://cloud.githubusercontent.com/assets/1223565/25263205/804ae43a-2666-11e7-830a-fc4b50ad0c43.png)

---

@molant I think this can be closed.
