### ISSUE TITLE
CSS Zoom support for mobile WebView

### ISSUE THREAD

**Issue by CMay** [MicrosoftEdge/Status#497]
I'm aware that CSS zoom factor works properly on desktop/mobile Edge and desktop WebView, but on my phone the zoom factor does nothing in a WebView.

I'm unsure if it's disabled in WebView Mobile, if it's just the version I'm using or what.  I thought it might be something I have to implement myself, but that can't be the case since it works in a desktop WebView.  I need this style to work reliably across desktop/mobile in a WebView.

Does the feature get disabled on mobile if the device's display settings have the content scaling set to something other than the default?

To be explicit, CSS transform: scale() works, but that is more like a zoom gesture rather than zoom factor which scales the content itself instead of the rendered view.  It seems to tap into the same function Edge uses for its built in Zoom option (ctrl+scrollwheel).

I tested in a WebView both with my own code as well as with this page: https://css-tricks.com/almanac/properties/z/zoom/

As an aside, is there a better place to keep track of WebView feature status and WebView issues?

Thanks!

**Comment by alrra** [comment]
> on my phone the zoom factor does nothing in a WebView.

@CMay This project is not the right place to report bugs in Microsoft Edge. Can you open an issue in our [issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/)? Thanks!

**Comment by CMay** [comment]
Thanks Cat, I wasn't sure where WebView issues go.  I've opened the issue here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10946333/
