### ISSUE TITLE
When the responsive design narrows so that Platform Status is above Get Tools, it is no longer a link

### ISSUE THREAD

**Issue by adrianba** [MicrosoftEdge/Status#51]
Not sure if this is on purpose (and if so why).

![capture](https://cloud.githubusercontent.com/assets/2166064/2999800/e085eaea-dd1a-11e3-9fa6-45f09064d67e.PNG)

**Comment by dstorey** [comment]
I think this was introduced in the menu refactoring. It isn't an issue in the dev branch where we changed the menu to be more like the new Modern.IE. Instead, it has the opposite problem, where the link is also includes all the free space.
