### ISSUE TITLE
Missing voting link/status for RTC Data Channels

### ISSUE THREAD

**Issue by 1000i100** [MicrosoftEdge/Status#529]
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/rtcdatachannels/#rtcdatachannels

https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17929639-rtc-data-channels

**Comment by Joffrey** [comment]
Microsoft should really implement this feature.

**Comment by alrra** [comment]
Thanks, @GammaNu!
