### ISSUE TITLE
WebAssembly is now enabled by default on build 16241

### ISSUE THREAD

**Issue by saschanaz** [MicrosoftEdge/Status#533]
Currently the status page only says:

>Preview in: Windows Insider Preview Build 15063+ by enabling in about:flags

Can we add something like _Unprefixed version: Windows Insider Preview Build 16241_?

**Comment by ctolkien** [comment]
I couldn't spot this in the change log - was this announced somewhere or just something you noticed?

Would like to update caniuse.com too.

**Comment by saschanaz** [comment]
@ctolkien It seems it's not publicly announced but you can access `WebAssembly` object on console and it can run [the demo on webassembly.org](http://webassembly.org/demo/) well without the `about:flags` thing. I think this is the result of [ChakraCore update](https://github.com/Microsoft/ChakraCore/pull/2447).

**Comment by alrra** [comment]
Cc @kypflug

**Comment by kypflug** [comment]
Thanks @SaschaNaz and @ctolkien - this is accurate and I've updated the changelog entry accordingly. I'll put in a PR to correct the Status entry.
