### ISSUE TITLE
IE version filters are backwards

### ISSUE THREAD

**Issue by jacobrossi** [MicrosoftEdge/Status#54]
Choosing "supported in IE8+" returns more features than "supported in IE11+".  But IE11 has more features than IE8, so I think we've got the filtering logic backwards.

**Comment by molant** [comment]
Mmm,I think this is what we agreed the other day and that's why I changed it. I believe it was meant to be something like
Features Implemented since this version.

It takes nothing to do the change, just let me know what should be the expected behavior.

-----Original Message-----
