### ISSUE TITLE
"Preview In"build numbers show as null when prefixed

### ISSUE THREAD

**Issue by kypflug** [MicrosoftEdge/Status#545]
Status entries where the most recent build number is an "iePrefixed" value, and either/both the ieStatus "text" value is "Preview Release" or "flag" is true, are showing blank or null for "Preview In:" where the build number should be displayed.

Example entries: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/subresourceintegrity/ and https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webauthenticationapi/

![image](https://user-images.githubusercontent.com/8116680/29835137-e43d80d8-8ca5-11e7-9f02-4543d03456fe.png)

![image](https://user-images.githubusercontent.com/8116680/29835149-f23292f0-8ca5-11e7-9cd3-98c7329b0f78.png)

**Comment by alrra** [comment]
@kypflug I've open this issue in the backend repository since this repository is only for the data.
