### ISSUE TITLE
Investigate using SVG sprites

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#55]
A number of the current items would be suitable as SVGs (MS and IE logos, the category logos, etc) and it would reduce the fuzzies on High DPI screens. We currently use one file per SVG.

We should investigate SVG sprite solutions so we can switch those icons over.

One downside would be probably having to use inline SVG rather than an external file. Another is that the raster images are highly optimised so may mean higher file size, but I’ve found a tool that does a decent job of cleaning up SVG files  and GZIP should also help. Current IE logo is 313 bytes vs 814 byes for a similar (optimised) SVG version.

**Comment by jonathantneal** [comment]
:thumbsup: and you could use external files with my [script](https://github.com/jonathantneal/svg4everybody) if the caching is worth it.

**Comment by dstorey** [comment]
Closing this as the site is now part of wider modern.ie. We will used a general solution for the entire site.
