### ISSUE TITLE
requestIdleCallback is supported since Firefox 55

### ISSUE THREAD

**Issue by digitarald** [MicrosoftEdge/Status#553]
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/requestidlecallback/

Chrome got the right status: https://www.chromestatus.com/features/5572795866021888 , just like Firefox's status board: https://platform-status.mozilla.org/#request-idle-callback

**Comment by molant** [comment]
@digitarald chromestatus shows public support for Firefox, same as Edge: 
![image](https://user-images.githubusercontent.com/606594/32122683-119cff88-bb16-11e7-9433-ac5439b91b25.png).

Can you please open an issue in [their repo](https://github.com/GoogleChrome/chromium-dashboard/issues). [Our entry](https://github.com/MicrosoftEdge/Status/blob/bd1aea4ea09d576fe174e6b54d2d078f3aae20b7/status.json#L98) doesn't override any value coming from chromestatus, so when that data is updated it will reflect after a few minutes in https://developer.microsoft.com/en-us/microsoft-edge/platform/status/requestidlecallback/

Thanks!
