### ISSUE TITLE
Server Workers supported behind flag in RS3

### ISSUE THREAD

**Issue by gsnedders** [MicrosoftEdge/Status#557]
Per https://github.com/w3c/web-platform-tests/pull/8394#issuecomment-346121804, which I think means its status should be "Preview"?

**Comment by alrra** [comment]
Cc: @kypflug can we get the exact version number? Thanks

**Comment by kypflug** [comment]
I didn't realize this was not marked as flagged - that's unfortunate. It should be in preview behind a flag starting in 16299, though not fully functional.

We'll be flipping this to on by default very soon in preview builds - to avoid randomization it may be best to change the status to preview alongside that change for clarity.

**Comment by alrra** [comment]
> We'll be flipping this to on by default very soon in preview builds - to avoid randomization it may be best to change the status to preview alongside that change for clarity.

👍

**Comment by saschanaz** [comment]
Looks like this can be closed now, as the page now marks it as `supported`.
