### ISSUE TITLE
Numeric keypad 0 doesn't zoom to normal

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#568]
Hey guys, this is just a question / conversation. Feel free to close it as it's unrelated to Status. I just wanted to let you to know if you ever feel like WTH when trying to zoom to normal using numeric keypad, you are not alone..

Consider this jargon:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Qwerty.svg/799px-Qwerty.svg.png" />

<small>from: https://en.wikipedia.org/wiki/Numeric_keypad#/media/File:Qwerty.svg</small>

In Firefox and Chrome running on Windows,

1. `Ctrl, +` zooms in when pressed on:
  a. numeric keypad
  b. typewriter keys
2. `Ctrl, -` zooms out when pressed on:
  a. numeric keypad
  b. typewriter keys
3. `0` zooms to normal when pressed on:
  a. numeric keypad
  b. typewriter keys

In IE and Edge, except for 3a., the rest work.

Assuming we consider lack of 3a. is a UX bug which was there in Internet Explorer since version 7 (oldest one I could try) and unfortunately now Edge has inherited this behavior from IE .. will it be fixed in future or is it some kind of a design decision?

**Comment by NoNameProvided** [comment]
This repo is for tracking the roadmap for EdgeHTML.

You should close this and report it at the [EdgeHTML issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/)

**Comment by molant** [comment]
Thanks @kasper3

As @NoNamedProvided says, please open an issue in the tracker.
