### ISSUE TITLE
Few questions about the website

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#574]
## Versioning

In Edge -> Settings and more -> Settings, there is a section called `About this app` at the bottom, which looks like:

> ### About this app
>
> Microsoft Edge 41.16299.15.0
> Microsoft EdgeHTML 16.16299
> &copy; 2017 Microsoft

In Status page, the versions are listed as:

> Build Number 16241+
> Build Number 17063+

etc.

Are these build numbers corresponding to second part of `41.16299.15.0` (version string)? If so, then it's extremely confusing as it's not the semantic versioning (https://semver.org).

## Preview 

Looking at: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/apngimageformat/?q=edge%3A'Preview%20Release', is the `Preview` filter indicating that this technology is in preview build of Edge, or technology is in preview (regardless of edge version prerelease or GA)? If it's former then seems like the information is outdated; latest GA is `41.16299.15.0` and page is stating some preview items with `16241+` .

**Comment by molant** [comment]
> Are these build numbers corresponding to second part of 41.16299.15.0 (version string)?

Yes

> is the Preview filter indicating that this technology is in preview build of Edge, or technology is in preview (regardless of edge version prerelease or GA)? If it's former then seems like the information is outdated; latest GA is 41.16299.15.0 and page is stating some preview items with 16241+ .

The technology is in preview starting for the given version. Once the engineering team considers it `done`, the status will switch to shipped. The build number there indicates the first version where it was introduced.

Can you give a more concrete example of where the information is outdated?

**Comment by styfle** [comment]
@kasper3 I agree that the build number is confusing and it's hard to know which EdgeHTML major version it corresponds to.

@molant I would prefer the Microsoft EdgeHTML version listed on the Status page.

For example, compare `URLSearchParams` listed on [Can I Use](https://caniuse.com/#feat=urlsearchparams) vs [MS Status](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/urlsearchparams/?q=urlsearchparams).

The Can I Use chart is much clearer and shows a release date which is what most developers would want to know.

How can you even match a build number to the EdgeHTML major version it corresponds to?

**Comment by molant** [comment]
I agree that version numbers are not very intuitive but unfortunately there's nothing we can do at this time to change them.

> How can you even match a build number to the EdgeHTML major version it corresponds to?

Taking the previous example: 41.16299.15.0
The important part is 16299. From there, you can get the version getting the first 2 digits. In this case it will be Edge 16.

With your example of `URLSearchParam`, that feature is currently in an insider build and not in the stable channel but when it ships it will be in Edge 17.

We could look into adding the Edge version on top of the build if this is something that people start requesting (at least for shipped features).

**Comment by ghost** [comment]
@molant, what does `41` indicate?

**Comment by molant** [comment]
@kasper3 `41` is the version number of the Edge app. It doesn't show up in the user agent so it shouldn't matter for developers.

**Comment by ghost** [comment]
Thanks @molant! I have all the information I need.

Btw, congrats on new release. New Edge (v42.17134.1.0) looks nice! I know this is not the right place to report the bug, but I have found a really annoying bug in new version using GitHub.com!

Input:

```
Hello

World!
```

in this github's comment box and hit preview, it shows:

```
Hello World!
```

expected behavior is same as input (without eating line breaks).

I am guessing folks already have reported it on developer.microsoft.com, but honestly this is something that really should be fixed soon.
