### ISSUE TITLE
RTC Data Channel - Status may be out of date

### ISSUE THREAD

**Issue by wanecek** [MicrosoftEdge/Status#575]
It is my understanding that WebRTC DataChannels are implemented in Safari and Opera, making MS Edge the last browser to add support.

If my understanding of the situation is correct, the feature ["RTC Data Channels"](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/rtcdatachannels/) (under category "Multimedia") is currently showing outdated browser support information on status.microsoftedge.com. 

Submitting a PR to fix this.

---

- [Announcement](https://webkit.org/blog/7726/announcing-webrtc-and-media-capture/) of WebRTC support in Safari
- Ran a [basic test](https://doubango.org/webrtc/samples/web/content/datachannel/) on Safari and Opera
- `'createDataChannel' in RTCPeerConnection.prototype` evaluates to `true` in Safari and Opera

**Comment by alrra** [comment]
> - Ran a [basic test](https://doubango.org/webrtc/samples/web/content/datachannel/) on Safari and Opera

Maybe I'm missing something, but that example doesn't seem to work in [Safari](https://user-images.githubusercontent.com/1223565/35572592-cd1bd690-0589-11e8-9c1f-e816372da474.png).

**Comment by wanecek** [comment]
Welp, this is certainly embarrassing. Sorry about that, I really shouldn't have blindly relied on 2nd hand information.

I'm currently a bit confounded when it comes to the support of datachannels in Safari, and will have to get back to you on this. I can't find any official documents, posts or demos supporting that it actually is supported, but I at the same time, I'm more than able to use it myself. I'll close this PR and reopen a new one including the updated status of Opera while I investigate this further.

**Extra info:**
I was confident in data channels working on Safari, mainly because of a non-public project I've worked on for the past months, relying heavily on datachannels and working fine in Safari 11 (when coupled with [webrtc-adapter](https://github.com/webrtc/adapter)). Naturally, I see how this narrative ("it works on my secret project") isn't convincing nor a reliable piece of information, so I will do my best to find a more credible source establishing the fact that RTCDataChannels are implemented since [Safari 11.0](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_0.html).

**Comment by molant** [comment]
We've talked internally and @angelokai has pointed us to https://webrtchacks.com/safari-webrtc/

It looks like data channels are supported but only in video chat scenarios. It's that aligned with your project @wanecek?

**Comment by wanecek** [comment]
Thank you! Unfortunately, our situation is quite the opposite :) We're not using `getUserMedia` or other means to obtain video/audio input from the user's device. Instead we're using dataChannels, one to send binary data (arraybuffers of images, videos, and other uploaded files) and one to send bulk data (mostly json messages).

I found that ["A Close Look Into WebRTC"](https://webkit.org/blog/7763/a-closer-look-into-webrtc/) mentions that `RTCDataChannel` is available:

> For developers that use WebKit in their apps, `RTCPeerConnection` and `RTCDataChannel` are available in any web view, but access to the camera and microphone is currently limited to Safari.

**Comment by wanecek** [comment]
Hi again! I got in touch with one of the WebKit developers, who confirmed that WebRTC DataChannels are implemented in Safari 11. They wrote the following.

> Yes Safari 11 supports RTCDataChannels. You can verify this by opening Web Inspector and in the Console tab, entering the following lines:

```javascript
var connection = new RTCPeerConnection();
connection.createDataChannel("sendChannel");
```

> The expected output is along the lines of:

```
RTCDataChannel { label: "sendChannel", ordered: true, maxPacketLifeTime: null, maxRetransmits: null, protocol: "", ...}
```

> If it were not supported you would see an error.

**Comment by alrra** [comment]
Cc: @AngeloKai

**Comment by alrra** [comment]
Thanks, @wanecek!
