### ISSUE TITLE
RTCDataChannels implemented in Opera

### ISSUE THREAD

**Issue by wanecek** [MicrosoftEdge/Status#577]
It seems as if WebRTC DataChannels have been implemented in Opera, which would implicate that the feature ["RTC Data Channels"](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/rtcdatachannels/) (under category "Multimedia") is currently showing outdated browser support information on status.microsoftedge.com. 

**References**
- [iswebrtcreadyyet.com](http://iswebrtcreadyyet.com/legacy.html#dataChannels)
- [MDN RTCDataChannel](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel#Browser_compatibility)

**Comment by alrra** [comment]
@wanecek I've [updated the information for Opera](https://github.com/MicrosoftEdge/Status/commit/15bef2fc1ef0108f54c13907b39accf088e0c9fe). Thank you!
