### ISSUE TITLE
Browser support of `conic-gradient` is out of date

### ISSUE THREAD

**Issue by keithclark** [MicrosoftEdge/Status#579]
CSS `conic-gradient()` is currently "in development" in Chrome (supported in stable behind a feature flag) and Safari. However, Platform Status is showing "Not supported".

**Comment by alrra** [comment]
@keithclark Thanks for opening this issue! 

---

I will add the missing [Chrome Status ID](https://www.chromestatus.com/features/5706155347148800) so that we automatically get the data from them.
