### ISSUE TITLE
Encode special characters in RSS

### ISSUE THREAD

**Issue by shhnjk** [MicrosoftEdge/Status#589]
Please encode special characters (at least `<` and `>`) of test in the link.
There's a entry `<a href="https://developer.microsoft.com/en-us/microsoft-edge/platform/status/detailssummary">The status of <details>/<summary> was changed from "In Development" to "Under Consideration"</a>` in the [rss](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/rss/) which if you render as an HTML, `<details>/<summary>` will be treated as an HTML tag.

**Comment by molant** [comment]
Any reason why you closed this?

**Comment by shhnjk** [comment]
I figured out that this depends on RSS client. If RSS client is HTML-based, it would help if we change the existing model, but if RSS client is a text-based client (e.g. Twitter bot, Email), then it would be unreadable if we changed it. So I thought maybe it should be filtered by HTML client side.
