### ISSUE TITLE
Updates on responsive images sections

### ISSUE THREAD

**Issue by Wilto** [MicrosoftEdge/Status#59]
Hey guys—just wanted to drop a couple of updates on the `picture` element and `srcset` attribute items:

**`picture`**
- WebKit work is [now officially underway](https://twitter.com/yoavweiss/status/471573481273184256)!

**`srcset`**
- The “working draft or equivalent” link is pointing at the original `srcset` proposal, which is no longer being pursued by any vendors. The version being actively implemented is `srcset` as defined by the [`picture` specification](http://picture.responsiveimages.org/#relationship-to-srcset)
- Work is [well underway in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=870021), and should be landing soon!

I’m psyched to see this sort of transparency from the IE team. Keep up the great work!

**Comment by dstorey** [comment]
May need to update ChromeStatus data for parts of this,

**Comment by yoavweiss** [comment]
True. I'll update there.

**Comment by yoavweiss** [comment]
Done! :)

**Comment by jacobrossi** [comment]
Rock on! Thanks

**Comment by Wilto** [comment]
Not sure how the two link up—do the updates to ChromeStatus take care of all the points above?

**Comment by dstorey** [comment]
yes, we just pull in their features.json via XHR

**Comment by Wilto** [comment]
Hm. Looks like things have updated in http://status.modern.ie/imgsrcset, but I don’t think that addressed the link to the defunct `srcset` spec.

**Comment by dstorey** [comment]
The link to the spec is at https://github.com/InternetExplorer/Status.IE/blob/production/app/static/ie-status.json#L37

However the link it is pointing to is still being updated (latest today.) Is that still being pursued by Apple (the editors) ? Where should it link to? http://picture.responsiveimages.org/#parse-srcset-attr ?

**Comment by Wilto** [comment]
Hm. http://picture.responsiveimages.org/#relationship-to-srcset  might make the most sense as kind of an “overview” section, but we should probably explain how the spec redefines `srcset` in, y’know, human-words.

You okay with linking to that? I filed https://github.com/ResponsiveImagesCG/picture-element/issues/194 in the meantime.

**Comment by Wilto** [comment]
Oh—and the W3C spec was a fork of the old WHATWG `srcset` spec, which is being [replaced with the `picture` spec](http://www.whatwg.org/specs/web-apps/current-work/multipage/edits.html#embedded-content). We’ve already got the actual WebKit work underway based on the `picture` version, so it’s just a matter of the paperwork catching up.
