### ISSUE TITLE
canvas' `toBlob` implementation is not tracked by Edge

### ISSUE THREAD

**Issue by kumarharsh** [MicrosoftEdge/Status#592]
The Edge platform status website is not even tracking the `toBlob` method on canvas objects. Here is the relevant W3C Spec: https://www.w3.org/TR/html50/scripting-1.html#dom-canvas-toblob and the MDN documentation: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

Surprisingly, it was there in IE10 from what I see in MDN, but then removed from Edge/IE11. All other browsers support it.

**Comment by alrra** [comment]
@kumarharsh Care to open a pull request? Thanks!

**Comment by kumarharsh** [comment]
Sure. I was confused because there had been no discussion regarding this property earlier, so wanted a confirmation if this was an oversight or intentional.

**Comment by kumarharsh** [comment]
More relevant sources (for documentation):

* https://www.chromestatus.com/feature/4562033294966784
* https://bugs.chromium.org/p/chromium/issues/detail?id=67587
* https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/15107964-support-toblob-on-canvas

It's unclear if this property is there on safari, and on which version. Some of the code has landed in changesets atleast an year ago, but I can't find definitive detail about it:
* https://bugs.webkit.org/show_bug.cgi?id=148878
* https://stackoverflow.com/questions/40258028/canvas-toblob-is-not-recognized-as-a-function-in-safari

**Comment by dstorey** [comment]
Edge has this prefixed, which AFAICT is the same as IE10:

```
partial interface HTMLCanvasElement
{
    [Extension] Blob msToBlob();
};
```

**Comment by kumarharsh** [comment]
@dstorey thanks. I saw that in MDN, but forgot to check it in Edge and thus missed it in the PR. Updated now.
