### ISSUE TITLE
Update "Dock tools vertically" and "console.table" in UserVoice

### ISSUE THREAD

**Issue by mkurz** [MicrosoftEdge/Status#598]
Hi,

following UserVoice tickets can be marked as "completed":
* https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6225572-dock-tools-vertically
(See https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/whats-new#docking-to-the-right-in-microsoft-edge)
* https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6796750-console-table
(See https://developer.microsoft.com/en-us/microsoft-edge/platform/status/consoletable/?q=console.table)

**Comment by molant** [comment]
Done, thanks!
