### ISSUE TITLE
Add Dart and NaCl to the dashboard

### ISSUE THREAD

**Issue by DanTup** [MicrosoftEdge/Status#60]
It'd be good to have significant features of other browsers like these listed (I know Chrome doesn't have native Dart support, but I expect it will!). There are other "Not Planned" items listed; so this doesn't seem completely crazy.

Although I'm fairly sure you won't implement them, I don't know if there's actually any "official" word on these. It would aid devs making decisions if they knew where each browser vendor stood on each others attempts to push things forwards :)

**Comment by dstorey** [comment]
Now Chrome have decided not to pursue this, and Edge won't support Dart (https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6511262-add-the-dart-vm) I don't think it is worth adding Dart to the site.
