### ISSUE TITLE
Add display:contents

### ISSUE THREAD

**Issue by aldendaniels** [MicrosoftEdge/Status#608]
Chrome and Firefox both now support CSS `display: content` - a feature that is becoming important in frameworks like React where wrapper components may want to listen to browser events without affecting DOM layout.  https://caniuse.com/#feat=css-display-contents It would be great to track progress towards this on the edge status dashboard.

**Comment by FremyCompany** [comment]
The feature was implemented poorly in the other browsers and has <a href="http://adrianroselli.com/2018/05/display-contents-is-not-a-css-reset.html#A11y">accessibility issues</a>, so it is unlikely we would want to add support in Edge right now. 

If we were to add the feature on the status, it would be as "Not currently planned". 

To prioritize this, I would urge Chrome to fix its accessibility issues. When they do, maybe we can reconsider the feature.

**Comment by molant** [comment]
@aldendaniels there's a PR for this right now: https://github.com/MicrosoftEdge/Status/pull/609

**Comment by aldendaniels** [comment]
Thanks! I appreciate the quick follow up. FWIW, I think there are high-value use-cases for this feature that don't break accessibility - I'd be happy to elaborate if that would be useful and you can point me to an appropriate forum.

**Comment by HM100** [comment]
Firefox has fixed this in M62
