### ISSUE TITLE
User Voice ID of display: contents is wrong

### ISSUE THREAD

**Issue by shhnjk** [MicrosoftEdge/Status#610]
User Voice ID of following commit should points to [Implement the display: contents](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10938981-implement-the-box-generation-keywords-from-css-dis) instead of [Implement Web Share API](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/31563175-implement-web-share-api)

[https://github.com/MicrosoftEdge/Status/commit/4dd96ae1aa7987e72f38d8911aa113a7b76e35b9](https://github.com/MicrosoftEdge/Status/commit/4dd96ae1aa7987e72f38d8911aa113a7b76e35b9)

**Comment by alrra** [comment]
@shhnjk Good catch!

**Comment by shhnjk** [comment]
Credit goes to [SelenIT](https://twitter.com/SelenIT2/status/1004383202973306881) :)
