### ISSUE TITLE
Change status of SameSite cookie

### ISSUE THREAD

**Issue by shhnjk** [MicrosoftEdge/Status#616]
Edge shipped SameSite cookie with 6B update. Let's change the status to shipped!

**Comment by alrra** [comment]
@shhnjk Care to open a PR? Thanks!

Cc @kypflug

**Comment by shhnjk** [comment]
Added PR. But I'm not sure about the structure much so please review nicely :)

**Comment by alrra** [comment]
> But I'm not sure about the structure much so please review nicely :)

Sure, no problem. Thanks!

**Comment by shhnjk** [comment]
@alrra How can we change Edge supported build to 16299+? We only backported till RS3...

**Comment by mkurz** [comment]
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17140412-support-samesite-cookie-option needs update

**Comment by molant** [comment]
@shhnjk has it been backported to IE11 or just 16299? If it is IE11 and then 16299+ (but no prior versions of Edge) then we have a limitation in our system to show that. We can probably make a note if that's the case.

**Comment by molant** [comment]
@mkurz thanks! I've updated it.

**Comment by mkurz** [comment]
@molant Thanks! So this is backported to Edge 16 (16299)? Was the update actually released already?

**Comment by mkurz** [comment]
I am asking because I want to update the data on http://caniuse.com

**Comment by mkurz** [comment]
@shhnjk If IE11 - back until which Windows 10 release? https://blogs.windows.com/msedgedev/2018/05/17/samesite-cookies-microsoft-edge-internet-explorer/#TRZ8Gket00OyVm4H.97 says "...we plan to service Microsoft Edge and Internet Explorer 11 on the Windows 10 Fall Creators Update and newer to support same-site cookies as well..."

**Comment by molant** [comment]
@mkurz Fall Creators Update is 16299 or Edge 16.

**Comment by shhnjk** [comment]
Hi, SameSite cookie is available in both Edge and IE 11 in RS3+ builds (16299+). So it is supported in Windows 10 Fall Creators Update and newer.

**Comment by mkurz** [comment]
But it did roll out just now? Not with the RS3+ builds (16299+) itself last autumn?

**Comment by molant** [comment]
> But it did roll out just now? Not with the RS3+ builds (16299+) itself last autumn?

It rolled with an update, thus the backporting part that @shhnjk mentions [here](https://github.com/shhnjk)

I've updated the description of the item to clarify the Edge support: https://github.com/MicrosoftEdge/Status/commit/8e6f63ca4155a2dfce3fbc9d2e8030f715c801f5

**Comment by shhnjk** [comment]
We shipped SameSite cookie with June's security update (i.e. Patch Tuesday). Thus all users who installed June's security update received a SameSite cookie support in both Edge and IE 11 (assuming that the user is using RS3+).

**Comment by mkurz** [comment]
Sorry for being annoying... But:

@shhnjk says
> Hi, SameSite cookie is available in **both Edge and IE 11 in RS3+ builds (16299+)**. So it is supported in Windows 10 Fall Creators Update and newer.

and

> Thus all users who installed June's security update received a SameSite cookie support in **both Edge and IE 11 (assuming that the user is using RS3+)**.

@molant based on these two statements, why not just change the build number to `16299` in
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/samesitecookies/ and remove the extra note ("_On Edge this feature..._")? These two statements say that also for IE11 16299 is the "first" Windows 10 RS update that has support for same site cookie.
Why does it say 10240+ when, based on these statements, it's available in 16299+ (which equals RS3+)?

What am I missing here?

**Comment by mkurz** [comment]
What I want to say is you have to use at least RS3+ (which is Windows 10 build 16299) to use it with IE11 (or Edge). Any IE11 and Edge installed on a Windows build lower than 16299 will never ever receive that feature.
Since 16299 is the **Windows** build version (and not Edge specific) I do not understand why the Status page shows 10240+ when for both IE and Edge the Windows build version 16299+ is needed...

**Comment by molant** [comment]
>  I do not understand why the Status page shows 10240+ when for both IE and Edge the Windows build version 16299+ is needed

Because I thought we backported it to IE11 in all Windows versions so I set the supported version to IE11 and the way the system assumes that if a feature is in IE11 it is automatically in Edge.

I'll update the version status.
