### ISSUE TITLE
Documentation link for "JavaScript module import()" is incorrect

### ISSUE THREAD

**Issue by antross** [MicrosoftEdge/Status#621]
This is also referred to as "dynamic imports". It differs from ES6 modules in that it allows importing code at runtime (whereas ES6 modules only enable static linking). 

The current link to MDN only discusses static imports. This link should probably be removed in favor of the existing link to the feature proposal on GitHub.

**Comment by patrickkettner** [comment]
@antross wanna pr?

**Comment by antross** [comment]
@patrickkettner already working on it. ;)
