### ISSUE TITLE
Documentation link for "Modules (ES6)" is incorrect

### ISSUE THREAD

**Issue by antross** [MicrosoftEdge/Status#622]
This is pointing to an unrelated "JavaScript code modules" documentation page on MDN which has nothing to do with this standard. It should be updated to point to the [MDN documentation for import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) instead.

**Comment by alrra** [comment]
@antross Feel free to just open a PR directly.
