### ISSUE TITLE
Use MDN's browser-compat-data for browser status info

### ISSUE THREAD

**Issue by connorshea** [MicrosoftEdge/Status#625]
[browser-compat-data](https://github.com/mdn/browser-compat-data) is a project by the team at MDN to track browser support for pretty much every web feature. It's used to build the [browser compatibility tables on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap#Browser_compatibility).

Using the BCD package would do a few things:

- The Edge Status site would have more accurate, up-to-date data on external browser support
- This would help to centralize the data in a single place for multiple browser vendors to contribute
- The data could be more granular, e.g. including the specific browser version a given feature was implemented in, or whether the browser implements all of the subfeatures for a given API.
- It could provide MDN URLs for "free" since almost every feature in the dataset has an associated MDN URL.

One example where data would be improved: [`Array.prototype.includes` is listed as "in development" for Firefox on Edge Status](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/arrayprototypeincludeses2016/), but [the MDN article lists it as having been supported since Firefox version 43](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility). There are likely problems like this throughout the current status site.

I imagine this could be implemented by adding the "feature path" (e.g. the [`Array.prototype.flatMap()` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) is represented as [`javascript.builtins.array.flatMap`](https://github.com/mdn/browser-compat-data/blob/aab36efd45422b8f1f60e5fe82ad912c5ad0e5f0/javascript/builtins/Array.json#L543)) as an optional attribute of a feature in the `status.json` schema.

A script could then be used to update the info in the `status.json` file by taking the data from the browser-compat-data package, parsing it, and then representing it using the existing format in `status.json`.

**Comment by patrickkettner** [comment]
hi! Im patrick, and im on both the Edge team and the MDN PAB. This is actually something we have been discussing. Both of my teams are working towards making this happen, and hopefully the change will be made soon. There is some infrastructure changes that are needed in order to satisfy some usage guidelines in this case

**Comment by alrra** [comment]
> . Both of my teams are working towards making this happen, and hopefully the change will be made soon. There is some infrastructure changes that are needed in order to satisfy some usage guidelines in this case

@patrickkettner Thanks for the extra information!

---

Closing this until we have something more tangible to address.
