### ISSUE TITLE
Webauthn status is out of date for Chrome, Firefox

### ISSUE THREAD

**Issue by alex** [MicrosoftEdge/Status#626]
<img width="1457" alt="screen shot 2018-07-31 at 9 50 01 am" src="https://user-images.githubusercontent.com/772/43464068-1a08d63a-94a8-11e8-94b1-428905252375.png">

Both Firefox and Chrome have been shipping webauthn for several releases.

**Comment by alrra** [comment]
Thanks, @alex!

**Comment by alex** [comment]
Nice! Thanks for the quick turnaround.
