### ISSUE TITLE
Add Generic Sensor-based motions sensors

### ISSUE THREAD

**Issue by anssiko** [MicrosoftEdge/Status#629]
The Generic Sensor-based motions sensors define a modern low-level API that is expected to supersede [Device Orientation](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/deviceorientation/) and [Device Motion](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/devicemotion/) (both supported in Edge):
- Accelerometer / [Established standard (CR)](https://www.w3.org/TR/accelerometer/) / [CanIUse](https://caniuse.com/#feat=accelerometer)
- Gyroscope / [Established standard (CR)](https://www.w3.org/TR/gyroscope/) / [CanIUse](https://caniuse.com/#feat=gyroscope)
- Magnetometer / [Established standard (CR)](https://www.w3.org/TR/magnetometer/) / [CanIUse](https://caniuse.com/#feat=magnetometer)
- Orientation Sensor / [Established standard (CR)](https://www.w3.org/TR/orientation-sensor/) / [CanIUse](https://caniuse.com/#feat=orientation-sensor)

Notes:

* The APIs ship in Chrome 67 and later, See [Chrome Platform Status](https://www.chromestatus.com/feature/5698781827825664)
* Specs at Candidate Recommendation i.e. W3C invites implementations
* As of Aug 2018, global adoption >50% per CanIUse.com
* Some Libraries that depend on the APIs:
  * https://github.com/immersive-web/webvr-polyfill
  * https://github.com/immersive-web/webxr-polyfill
  * https://github.com/kenchris/sensor-polyfills (polyfill)
* Demos:
  * https://intel.github.io/generic-sensor-demos/
* Articles:
  * https://mobiforge.com/design-development/the-generic-sensor-api
  * https://developers.google.com/web/updates/2017/09/sensors-for-the-web

**Comment by alrra** [comment]
@anssiko Want to open a PR? Thanks!

**Comment by anssiko** [comment]
@alrra, sure!

Should I omit the `ieStatus` field in the PR to be filled in by you folks? Or is there a default state for new features?

(I'll link to the chromestatus.com `id` that I assume allows me to omit `impl_status_chrome`.)

**Comment by molant** [comment]
@anssiko IIRC the default we use is:

```js
"ieStatus": {
      "text": "Under Consideration",
      "priority": "Low"
    },
```

**Comment by alrra** [comment]
> Should I omit the ieStatus field in the PR to be filled in by you folks?

Include it, and we will figure out the correct one before merging.

@kypflug What is the current status for this?

>  Or is there a default state for new features?

If we have not said anything publicly: `"Under Consideration"`.

> (I'll link to the chromestatus.com id that I assume allows me to omit impl_status_chrome.)

Yes, if you provide the chrome status ID, we get the data for all other browsers from there.

**Comment by anssiko** [comment]
@alrra, submitted a PR #630. Feel free to adjust the `ieStatus` as needed, now defaulted to "Under Consideration".

**Comment by alrra** [comment]
@anssiko Thanks!
