### ISSUE TITLE
Screen Capture API status misleading

### ISSUE THREAD

**Issue by wanecek** [MicrosoftEdge/Status#632]
The status page shows that Screen Capture is supported from 17134+. While this is partly true, it only works on Windows Pro/Enterprise, i.e. not Windows Home (finally confirmed in https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17357055/). 

To clarify this, I suggest the status page is either updated with a note explicitly stating the partial support, or changed to "In Development" (since it will be fixed in RS5).

Personally I would prefer the latter, since there (as far as I can tell) does not exist any way in which you can tell if a client is using Windows Home or Pro/Enterprise using javascript.

**Comment by molant** [comment]
For those following this issue, it has been closed in https://github.com/MicrosoftEdge/Status/commit/0139774069f4ca98085c480a49f90f9d4d043152

with the following changes: 

* Note that it only works on Win 10 Pro and Enterprise
* Update the platforms to be only desktop

**Comment by wanecek** [comment]
Great, thank you :) I'd still argue that it's too easy to miss. I would prefer to have it inverted, i.e. to say that it's supported in 1803+ with the caveat that it works for some users (Windows Pro/Enterprise) in 17134+. But it's still an improvement, thanks :+1:
