### ISSUE TITLE
Progress element's value attribute(with 0) is removed when assigned through innerHTML

### ISSUE THREAD

**Issue by vradhika17** [MicrosoftEdge/Status#637]
Issue with progress element  rendering when copied through innerHTML. 
When progress value is 0 and copied the innerHTML and assign to another DOM element removing the value attribute which is causing fluctuating progress element.  For test code, refer https://plnkr.co/edit/571GILcvmS0JKDmwkPqJ?p=preview .

**Comment by alrra** [comment]
@vradhika17 This project is *not* for reporting bugs in Microsoft Edge and/or Internet Explorer. Browser feedback can be provided through the [issue tracker](https://developer.microsoft.com/microsoft-edge/platform/issues/).
