### ISSUE TITLE
no mention of HTTP status 308

### ISSUE THREAD

**Issue by reschke** [MicrosoftEdge/Status#64]
...defined in RFC 7238 (to be published next week), implemented in all desktop user agents except IE. (see http://greenbytes.de/tech/tc/httpredirects/#l-308 for test cases)

**Comment by jacobrossi** [comment]
Individual response codes are at a level of granularity that's probably too specific for status.IE  If you haven't already, I think the right place to post this is http://connect.microsoft.com/ie

**Comment by reschke** [comment]
"fetch me another stone"?
