### ISSUE TITLE
Update Firefox status for prefers-reduced-motion media query

### ISSUE THREAD

**Issue by JamesCatt** [MicrosoftEdge/Status#647]
This feature doesn't seem to be listed in Chromium Status (although it's being "[actively worked on](https://bugs.chromium.org/p/chromium/issues/detail?id=722548#c27)"), which may be why the Edge status is out of date.

Also [not listed in FF status](https://github.com/mozilla/platform-status/issues/563), even though it shipped in v63 ([Windows](https://bugzilla.mozilla.org/show_bug.cgi?id=1365045), [macOS](https://bugzilla.mozilla.org/show_bug.cgi?id=1475462)).

Happy to help with PR.

**Comment by molant** [comment]
A PR will be great. Thank you!


________________________________
