### ISSUE TITLE
SVG `use` with external source

### ISSUE THREAD

**Issue by jonathantneal** [MicrosoftEdge/Status#65]
Creating the issue to track consideration of SVG `<use>` with external sources.

@dstorey filed a related issue (#55) to switch to SVGs on your main site. However, he notes:

> One downside would be probably having to use inline SVG rather than an external file.

This has been written about elsewhere:

> External resource doesn't work in any version (up to 11 tested) of Internet Explorer. Even the ones that do support inline SVG: 9, 10, 11. — [CSS Tricks](http://css-tricks.com/svg-use-external-source/)

So, I asked about this, and you responded. Thank you!

> This is currently "Under Consideration," we'll add it to http://status.modern.ie  for you to be able to track. #AskIE — [@IEDevChat](https://twitter.com/IEDevChat/status/472066351633149954)

And here we are. Again, the issue is limited to IE9-11. I’ve yet to find a way to detect the issue apart from user agent sniffing. I’m maintaining a [shiv](https://github.com/jonathantneal/svg4everybody), and I will link to this status once it is available.

**Comment by jonathantneal** [comment]
Kudos to @gregwhitworth for tracking this feature with f240b6d. I’m closing this.

**Comment by gregwhitworth** [comment]
No problem, sorry it took me a bit to get it posted :)
