### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by ststeiger** [MicrosoftEdge/Status#654]
I can haz Microsoft Edge 4 Linux pls ? ;)

[![InterTroll](https://memegenerator.net/img/images/10421315.jpg)](https://memegenerator.net/Internet-Explorer-Trollface)

**Comment by molant** [comment]
Hi @ststeiger 
From the main readme.md

> Note that this GitHub project is not for making feature requests for or reporting bugs in Internet Explorer or Microsoft Edge. 

Best way to provide this feedback if you don't have a Windows machine is to tweet at [@MSEdgeDev](https://twitter.com/MSEdgeDev).

Thanks for your interest in having Edge in more platforms!
