### ISSUE TITLE
Translate with Google by right menu of Microsoft Edge .

### ISSUE THREAD

**Issue by jianboy** [MicrosoftEdge/Status#655]
I am a Chinese. I want Microsoft can develop a function :

Translate with Google by right menu of Microsoft Edge . Not google translate plugin !

![2019-05-16_165313](https://user-images.githubusercontent.com/11532015/57840416-27382b80-77fb-11e9-8db7-67afaec25714.png)

**Comment by molant** [comment]
From the main readme.md

> Note that this GitHub project is not for making feature requests for or reporting bugs in Internet Explorer or Microsoft Edge. 

Best way to provide this feedback is via the smiley in the top right of the browser or  if you don't have a Windows machine via a tweet at [@MSEdgeDev](https://twitter.com/MSEdgeDev).

Thanks
