### ISSUE TITLE
I want a function : Edge reading later

### ISSUE THREAD

**Issue by jianboy** [MicrosoftEdge/Status#656]
Edge has a good function is reading later. 
![BaiduHi_2019-5-16_16-58-21](https://user-images.githubusercontent.com/11532015/57840865-045a4700-77fc-11e9-8e89-fd21a8642297.png)

but update to microsoft edge with Chromium. it disappear.

**Comment by molant** [comment]
From the main readme.md

> Note that this GitHub project is not for making feature requests for or reporting bugs in Internet Explorer or Microsoft Edge. 

Best way to provide this feedback is via the smiley in the top right of the browser or  if you don't have a Windows machine via a tweet at [@MSEdgeDev](https://twitter.com/MSEdgeDev).

Thanks
