### ISSUE TITLE
I want a function : Edge full screen with title when mouse is on top menu

### ISSUE THREAD

**Issue by jianboy** [MicrosoftEdge/Status#657]
I want a function : Edge full screen with title when mouse is on top menu. you can see it by blow gif:

![13](https://user-images.githubusercontent.com/11532015/57842510-42a53580-77ff-11e9-9647-b6e4c258d5ea.gif)

**I know edge and IE all can do it, but Microsoft Edge dev can not do it .**

**Comment by molant** [comment]
From the main readme.md

> Note that this GitHub project is not for making feature requests for or reporting bugs in Internet Explorer or Microsoft Edge. 

Best way to provide this feedback is via the smiley in the top right of the browser or  if you don't have a Windows machine via a tweet at [@MSEdgeDev](https://twitter.com/MSEdgeDev).

Thanks
