### ISSUE TITLE
I want a function : website login with windows pin

### ISSUE THREAD

**Issue by jianboy** [MicrosoftEdge/Status#658]
I know Edge can login microsoft website with windows 10 account.but Microsoft Edge dev can not do it .

**and ,the most important things is that plugin data and all plugin should sync with microsoft account !**

**otherwize, Microsoft Edge dev can not replace chrome and Edge .**

**Comment by molant** [comment]
From the main readme.md

> Note that this GitHub project is not for making feature requests for or reporting bugs in Internet Explorer or Microsoft Edge. 

Best way to provide this feedback is via the smiley in the top right of the browser or  if you don't have a Windows machine via a tweet at [@MSEdgeDev](https://twitter.com/MSEdgeDev).

Thanks
