### ISSUE TITLE
Google Translate

### ISSUE THREAD

**Issue by Naomi010Sentzke** [MicrosoftEdge/Status#661]
Microsoft Translate is not good enough for asian languages. Google Translate needs to be an option in both PC and android in the new android.

**Comment by molant** [comment]
Thanks @Naomi010Sentzke for opening an issue.
Unfortunately this is not the right place for submitting feedback as it will get lost.

The proper way is via the smiley icon available in the top right of [Edge in your PC](https://www.microsoftedgeinsider.com/en-us/) 

![image](https://user-images.githubusercontent.com/606594/66123689-efcbef00-e5e2-11e9-98eb-3502e72b709e.png)

or from the [Edge on Android App](https://play.google.com/store/apps/details?id=com.microsoft.emmx&hl=en_US).

Thank you
