### ISSUE TITLE
I'm not able to open new window or tab in edge browser (Using selenium)

### ISSUE THREAD

**Issue by Madhusudanpatidar** [MicrosoftEdge/Status#664]
:warning: Notes: 

  * This project is *not* the right place to make feature requests or report bugs in Microsoft Edge and/or Internet Explorer. Browser feedback can be provided through the [issue tracker](https://developer.microsoft.com/microsoft-edge/platform/issues/) and on [UserVoice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer).
  * For most of the features, the support data for browsers other than Microsoft Edge and Internet Explorer comes from the [Chromium Dashboard](https://www.chromestatus.com), so bugs related to that data should be filed [here](https://github.com/GoogleChrome/chromium-dashboard/issues).

I'm using selenium web driver tool to automate edge browser.
First issue:- Already opened edge browser so not able to open next browser using automation code.
Second issue:- First browser is lunched then I'm opening new tab or other window of the same browser using selenium web driver so not able to open new tan or window.

**Comment by Madhusudanpatidar** [comment]
I'm using selenium web driver tool to automate edge browser.
**First issue:-** Already opened edge browser so not able to open next browser using automation code. 
**Second issue:-** First browser is lunched then I'm opening new tab or other window of the same browser using selenium web driver **so not able to open new tan or window.**

**Comment by molant** [comment]
As you said in your comment, this is not the right place.

1. Is by design
2. Please share a minimum project where this is happening with detailed instructions  with @thejohnjansen via Twitter.
