### ISSUE TITLE
The information in readme.md and the bug reporting template are wrong.

### ISSUE THREAD

**Issue by kurgol** [MicrosoftEdge/Status#666]
```
  * This project is *not* the right place to make feature requests or report bugs in Microsoft Edge 
and/or Internet Explorer. Browser feedback can be provided through the [issue tracker]
(https://developer.microsoft.com/microsoft-edge/platform/issues/) and on [UserVoice]
(https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer).
```

When I click to submit a new issue I am presented with a warning, the first part of which is copied above. This warning tells me to log issues in Edge not through this issue tracker but either through the issue tracker or uservoice. This same information is presented in readme.md.

Neither of these address's work for me. The developer.microsoft.com just redirects to the microsoft-edge page. 

The uservoice forum appears to have been closed down.

![image](https://user-images.githubusercontent.com/15245142/73557892-fc097100-4449-11ea-8989-51a51e730a17.png)

Really I want to open  UI bug for Edge, but as the instructions here appear to be incorrect it would be great if you could update them with current info.

**Comment by molant** [comment]
Thanks @Kurgol,

to report UI bugs use the built-in feedback tool. You can invoke it pressing "Alt+Shift+i" or via the "..." menu.

**Comment by kurgol** [comment]
@molant I don't know how to send a PR to have the pre-filled text in a "new issue" input box, but that is also incorrect and should be updated. Presumably, someone with control of the repo will need to do that. 
![image](https://user-images.githubusercontent.com/15245142/73606100-9b3f7d00-459e-11ea-9a08-87e6d9ac5038.png)

**Comment by molant** [comment]
Can you please do a PR to modify the following file?
 
https://github.com/MicrosoftEdge/Status/blob/production/.github/ISSUE_TEMPLATE.md

Thank you

**Comment by Kurgol** [comment]
I believe this issue is now resolved, thanks to @molant for the guidance.

**Comment by kurgol** [comment]
I believe this issue is now resolved, thanks to @molant for the guidance.
