### ISSUE TITLE
Incorrect user agent on https://google.com

### ISSUE THREAD

**Issue by abhijeetnarvekar** [MicrosoftEdge/Status#671]
User agent displayed specifically on google.com website doesn't include edge.

Edge Chromium Version: 81.0.416.58 (Official build) (64-bit)

User agent on google.com
`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36"`

User agent on other websites:
`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36 Edg/81.0.416.53"`

**Comment by skewty** [comment]
Perhaps this is by design as it prevents malicious breakage of browser support based on user agent string. 
Yeah, malicious breakage of competing browsers really is a thing.

**Comment by skewty** [comment]
In the case of google.com it prevents Chrome advertising which tries to get the user to switch to Chrome.  MS does the same on some of their web sites.

**Comment by abhijeetnarvekar** [comment]
@skewty Thanks! That explains it !
