### ISSUE TITLE
Search broken on status.microsoftedge.com

### ISSUE THREAD

**Issue by mohamedmansour** [MicrosoftEdge/Status#672]
Search bar is broken on "Microsoft Edge Platform".
 https://developer.microsoft.com/en-us/microsoft-edge/status/​​​​​​​

**Comment by molant** [comment]
Ping @ststimac

**Comment by ststimac** [comment]
Yes, I'm aware of this and need to file a bug.

**Comment by ststimac** [comment]
I've filed a bug with the appropriate people and will update when I can. All filtering/search on that page seems to be broken/not affecting the page.

**Comment by olgamarti** [comment]
The problem is fixed in production. @ststimac can you verify it and close the issue? Thanks!

**Comment by ststimac** [comment]
This is all fixed. Thank you @olgamarti!
