### ISSUE TITLE
"[object Object] in Microsoft Edge (EdgeHTML)" for Box Alignment

### ISSUE THREAD

**Issue by brochington** [MicrosoftEdge/Status#677]
found "[object Object] in Microsoft Edge (EdgeHTML)" when looking at the Box Alignment statuses.

<img width="371" alt="Screen Shot 2020-05-14 at 12 13 53 AM" src="https://user-images.githubusercontent.com/3392188/81904620-5d2bff00-9578-11ea-97aa-88e806ab0b2e.png">

**Comment by olgamarti** [comment]
Hi! Thanks for report this issue. We did a deployment and the issue should be resolved.
