### ISSUE TITLE
CSS: resize and outline-offset props (CSS3 User Interface)

### ISSUE THREAD

**Issue by am11** [MicrosoftEdge/Status#68]
Spec: http://www.w3.org/TR/css3-ui/.

Please add CSS `resize` and `outline-offset` properties to your backlog ([#864315 @MS-Connect](https://connect.microsoft.com/IE/feedback/details/864315/css3-resize-and-outline-offset-properties-missing)). Couldn't find those on http://status.modern.ie/.

See Browser Support: http://www.w3schools.com/css/css3_user_interface.asp.

Thanks.

**Comment by am11** [comment]
@alrra, `outline-offset` has been added ([ref](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/cssoutlineoffset/?q=outline-offset)), but data for `resize` is still missing. `resize` has more user-voice votes than `outline-offset`: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6513977-css-resize-property.
Can this data be added to status feed?

**Comment by alrra** [comment]
> Can this data be added to status feed?

@am11 Care to open a pull request? Thanks!

(Cc: @gregwhitworth)

**Comment by alrra** [comment]
Closing in favor of #481.
