### ISSUE TITLE
Edge Dev 84.0.508.0 x64 Crashing With 0xc0000374

### ISSUE THREAD

**Issue by GingerGraham** [MicrosoftEdge/Status#683]
My install of Edge Dev upgraded to 84.0.508.0 today and now it consistently crashes out after ~10 seconds of runtime with a 0xc0000374 error written to the Windows Application Event Log

![image](https://user-images.githubusercontent.com/34165628/82376395-f2684100-9a19-11ea-8d32-fa847c88eabd.png)

Event Log:

Log Name:      Application
Source:        Application Error
Date:          19/05/2020 21:43:05
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      <removed>
Description:
Faulting application name: msedge.exe, version: 84.0.508.0, time stamp: 0x5eb37428
Faulting module name: ntdll.dll, version: 10.0.19041.207, time stamp: 0xcad89ab4
Exception code: 0xc0000374
Fault offset: 0x00000000000fdec9
Faulting process ID: 0x2c40
Faulting application start time: 0x01d62e1e0c1c4c23
Faulting application path: C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 6f796dac-621e-497a-9f29-e85899d9b694
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-05-19T20:43:05.0956601Z" />
    <EventRecordID>34070</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer></Computer>
    <Security />
  </System>
  <EventData>
    <Data>msedge.exe</Data>
    <Data>84.0.508.0</Data>
    <Data>5eb37428</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.19041.207</Data>
    <Data>cad89ab4</Data>
    <Data>c0000374</Data>
    <Data>00000000000fdec9</Data>
    <Data>2c40</Data>
    <Data>01d62e1e0c1c4c23</Data>
    <Data>C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data>
    <Data>6f796dac-621e-497a-9f29-e85899d9b694</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by GingerGraham** [comment]
I have WER mini and full dumps available if required.

The exception details are:

PROCESS_NAME:  msedge.exe

ERROR_CODE: (NTSTATUS) 0xc0000374 - A heap has been corrupted.

EXCEPTION_CODE: (NTSTATUS) 0xc0000374 - A heap has been corrupted.

EXCEPTION_CODE_STR:  c0000374

**Comment by nschonni** [comment]
> This project contains the data for status.microsoftedge.com, a portal for the latest implementation status and future roadmap for interoperable web platform features in Microsoft Edge and other browsers, including Internet Explorer.

**Comment by molant** [comment]
@GingerGraham can you please use the built-in feedback mechanism to report this issue or if it crashes too fast use the Windows Feedback app (Win + F). That way you can also track the status of the issue.
