### ISSUE TITLE
Desktop: OOTB sharing integrations

### ISSUE THREAD

**Issue by am11** [MicrosoftEdge/Status#69]
IE for modern desktop and WinPho is amazing. Features like ability to share pages, favorites across the devices and pin to start screen are awesome.

IE desktop on the other hand, with its old UI (century-old-looking 'internet options' dialog for instance, which can probably be redesigned using [MS-Office's backstage](http://office.microsoft.com/en-us/word-help/introducing-backstage-HA010372688.aspx) concept) has not been blessed with such sharing integrations. 

For that matter, I propose this: [#806762 @MS-Connect](https://connect.microsoft.com/IE/feedback/details/806762/ootb-sharing-options-in-internet-explorer)

![sharing-is-caring 1](https://cloud.githubusercontent.com/assets/3840695/3139016/fa48113a-e8c1-11e3-8ab5-f341e7374c9d.png)

I believe this will mitigate the feature disparity between modern and desktop versions to some extent.

Please consider adding this to your backlog.

Thanks in anticipation.

**Comment by jacobrossi** [comment]
Thanks for your feedback. However, this repository is for the code related to the http://status.modern.IE web site only. Suggestions and bug reports for Internet Explorer should be filed at http://connect.microsoft.com/ie (as you have already) and on Twitter @iedevchat.

**Comment by am11** [comment]
Thanks! I tweet it `@iedevchat`: https://twitter.com/adeelbm/status/474137944903544832.
