### ISSUE TITLE
[QUESTION] CNAME-uncloaking

### ISSUE THREAD

**Issue by Nomes77** [MicrosoftEdge/Status#701]
As FireFox and Brave support cname-uncloaking
and Adguard recently published a list of cname trackers
and uBlockOrigin already support it.

Is there a chance or when is Microsoft Edge going to implement cname-uncloaking?
Since cname cloaked tracker is getting a major problem.

**Comment by djj1109** [comment]
thank you

**Comment by Nomes77** [comment]
Is there any progress on this topic?

**Comment by Nomes77** [comment]
Half year ago. You 've still done nothing. Terrible!!
