### ISSUE TITLE
Add CSS `column-span: none` 

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#75]
Not sure if this is too fine grained for StatusIE but IE supports ye olde `column-span: 1` instead of `none`.

The current spec (`none`) is supported by Safari, Opera, and Chrome. (with prefix, except Presto versions of Opera)

Spec: http://www.w3.org/TR/css3-multicol/#column-span

**Comment by jacobrossi** [comment]
How about opening this up as a bug over at http://connect.microsoft.com/ie? I think this is too specific to be worth a feature listing.
