### ISSUE TITLE
Filters out of the blue area

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/Status#8]
Depending on the resolutions, the filters might be out of the blue area. This is happening at 750px with Chrome:
![image](https://cloud.githubusercontent.com/assets/606594/2639266/84d8e06a-bec2-11e3-9718-c9d7529785cf.png)

**Comment by molant** [comment]
@dstorey, any idea?

**Comment by dstorey** [comment]
Confirmed. Investigating

**Comment by dstorey** [comment]
Should be resolved now. Verify?
