### ISSUE TITLE
Add Fetch API

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#80]
Hot off the press.

spec: http://fetch.spec.whatwg.org/#fetch-api
announcement: http://lists.w3.org/Archives/Public/public-webapps/2014AprJun/0687.html

“The plan is to implement and ship this fairly soon” (by Mozilla I assume)

**Comment by am11** [comment]
This has been added: https://status.modern.ie/fetchapi.
Separately CSS3 User Interface is still missing: https://github.com/InternetExplorer/Status.IE/issues/68.
