### ISSUE TITLE
Tooltips over status text shows category instead of definition

### ISSUE THREAD

**Issue by charlesjmorris** [MicrosoftEdge/Status#86]
When mousing over status text like "In Development", it no longer shows the definition of the status. Instead it shows the category like "User Input", or "Network/Connectivity".

Works in Chrome if you mouse over the text directly, but seems broken in IE/FF.

**Comment by jacobrossi** [comment]
I think this may actually be a platform bug.  We switched to a button element for accessibility and other reasons. Looks like IE doesn't pull tooltips from descendent elements in a button. Filed a bug to track: https://connect.microsoft.com/IE/feedbackdetail/view/1028523/tooltips-not-shown-for-button-descendants
