### ISSUE TITLE
Add <keygen> element

### ISSUE THREAD

**Issue by charlesjmorris** [MicrosoftEdge/Status#88]
Probably not frequently used, but part of the HTML5 spec so should consider.

**Comment by adrianba** [comment]
I think the current status is this:
- IE correctly parses &lt;keygen> as a [void element](http://www.w3.org/TR/html5/syntax.html#void-elements)
- The [HTML5 spec says](http://www.w3.org/TR/html5/forms.html#attr-keygen-keytype) that "_it is possible for a user agent to not support any key types at all._" That's what IE currently does.

If we add &lt;keygen> to the site we should make sure to address the different aspects of the element.
