### ISSUE TITLE
Improve mobile ux issues

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Status#9]
- status is not visible on mobile
- category text nor icon can be accessed
- filters are hidden
- menu is hidden

We should be able to copy the modern.ie menu for mobile. The rest may be more tricky. 
perhaps we can show the feature headings on two lines to show the status/category?

**Comment by molant** [comment]
I'm ok having two lines as long as the item's height doesn't increase too much (I think we have space right now for the two lines). About the category icon is that something we really need to put on the header in mobile? With the name of the feature you usually have an idea of the bucket and we can always put it on the feature detail.
Thoughts?

**Comment by dstorey** [comment]
The category is something I’ve seen Sara Soueidan [comment on on Twitter](https://twitter.com/SaraSoueidan/status/451956314374418432), as we currently have a coloured line, and it means nothing (except users wondering what it means) when there is no other indication.  It doesn't necessarily need to be in the header or an icon, but if the category is useful on desktop then I suppose it is useful on mobile too. Especially as one can't sort/filter on mobile currently. For example, one might not know that "Filters" is CSS filters, as there is no CSS text in the header (nor body actually) and could easily be something else (SVG, maybe another graphics thing like Canvas or WebGL?)

**Comment by dstorey** [comment]
This was fixed by the filtering task and a fix for the status on the accessibility task
