### ISSUE TITLE
Filter on versions bug

### ISSUE THREAD

**Issue by Studio384** [MicrosoftEdge/Status#91]
When a user filters on Implemented in, you can select the version it has been implemented in. The radio buttons note options like IE9+. This suggests that it will show everything that has been added in IE9 and higher. However, the result is everything that has been added in IE9 and lower. This makes it a little bit confusing and harder to find technologies that have been added in IE11 or IE10, as the list gets longer. It should filter the way the labels describe, another, perhaps better, solution is making those radio buttons into checkboxes so we can filter on features that have been added in, for example, IE9 and IE11 without IE10 showing up.

**Comment by molant** [comment]
Hi @Studio384 

What we've tried to do with this filter is help developers know in an easy way what features they have available for the minimum browser they need to support so... it is working as expected.
If we changed the label from "Implemented in" to "Supported by" will it be clearer?
- @jacobrossi and @dstorey to get their opinions too.

**Comment by dstorey** [comment]
"supported by" label should make it clearer. We used to have the behaviour as described but changed it. Either way has value for different reasons.

**Comment by Nacimota** [comment]
I think the confusion stems from the use of **+** (as in IE8+, IE9+, etc.) in the filter drop-down. The intended meaning is (for example) "show only features supported since IE8" but reads to some users as "show only features implemented in IE8 _or above_"*.
