### ISSUE TITLE
Add CSS Font Loading API

### ISSUE THREAD

**Issue by KenjiBaheux** [MicrosoftEdge/Status#93]
Would love to see this API on modern.status.ie :)

**Comment by lakenen** [comment]
:+1: this would be really nice to have. It's already available in stable Chrome and (very soon) Firefox. http://caniuse.com/#feat=font-loading

**Comment by molant** [comment]
Tracked in https://developer.microsoft.com/en-us/microsoft-edge/platform/status/cssfontloadingapi/ (under consideration)
