### ISSUE TITLE
Add WOFF 2.0 (web font compression format)

### ISSUE THREAD

**Issue by KenjiBaheux** [MicrosoftEdge/Status#94]
We are seeing impressive gains over WOFF 1.0 web fonts: 30% gains on average, up to 50% for CJK web fonts. It would be great to have this on your radar at modern.status.ie !

**Comment by molant** [comment]
ID in Chromestatus json file is 6718644721549312

**Comment by ericlaw1979** [comment]
Firefox 35 adds WOFF2; currently behind an about:config flag for release builds; enabled by default in pre-release builds. https://bugzilla.mozilla.org/show_bug.cgi?id=1064737

**Comment by igrigorik** [comment]
In other news.. looks like it's disabled by default (ugh): https://twitter.com/igrigorik/status/555032966884495360
