### ISSUE TITLE
Feature: "Pointer Lock (Mouse lock)" not shipped in Opera

### ISSUE THREAD

**Issue by m910q** [MicrosoftEdge/Status#96]
Opera 12 and Opera 15+ does not support Pointer lock.

Opera 15+ returns true on this:
`'webkitPointerLockElement' in document`

But if you go and request a lock, nothing happens.

**Comment by dstorey** [comment]
CC @mathiasbynens

**Comment by m910q** [comment]
I have reported this to Opera as well. It's identified as DNA-22042.

Here's a jsfiddle to try it out in Opera: http://jsfiddle.net/RM58X/

**Comment by mathiasbynens** [comment]
Thanks for the report. I’ve CC’d some people on the internal bug ticket. Hopefully it can be resolved soon, as this breaks feature tests.

**Comment by jacobrossi** [comment]
I've temporarily overridden the Opera status for this feature (SHA: 139854b). Leaving this issue open to track removing the override once this is fixed in Opera.

**Comment by m910q** [comment]
Opera 23 is now shipped, which contains the pointer lock feature.
It's a bit buggy, but it's there. The bug is already fixed in their development build.
