### ISSUE TITLE
Allow finding most recently changed

### ISSUE THREAD

**Issue by jacobrossi** [MicrosoftEdge/Status#97]
We should consider adding an RSS feed or at least a "sort by last modified" option for discovering what features have changed recently.

https://twitter.com/The_Grand_User/status/478615351698391041

**Comment by molant** [comment]
This is related to #34, last week I started some initial concepts locally for the RSS but need to think a bit more about it

**Comment by molant** [comment]
@jacobrossi the easiest option will be to add a new field to the json with a date. That way sorting in the UI and creating an rss should be really easy.
The other (more complicated) approach will be checking the git commits of the json file and figuring out the diffs (at least for the RSS part).
Any other ideas?

**Comment by dstorey** [comment]
There is a community created site that tracks changes to status.ie: http://platformstatustracker.azurewebsites.net 

I think it checks the commits.

**Comment by dstorey** [comment]
Closing this and opened a bug in dev.modern.ie
