### ISSUE TITLE
Add navigator.hardwareConcurrency

### ISSUE THREAD

**Issue by eligrey** [MicrosoftEdge/Status#99]
navigator.hardwareConcurrency is supported by [Chrome 37, Opera 24, and the next version of Safari](http://www.chromestatus.com/features/6248386202173440).

**Comment by mramato** [comment]
I noticed that `navigator.hardwareConcurrency` doesn't even show up on https://status.modern.ie/  Is it safe to assume that's it's not even being considered; or is it simply not there because no one has opened a pull request to add it?

**Comment by eligrey** [comment]
It's supported in Edge 15 now. @jacobrossi would you mind updating the platform status page?

**Comment by alrra** [comment]
@eligrey Good catch, thanks!

> would you mind updating the platform status page?

I've opened https://github.com/MicrosoftEdge/Status/pull/513.
